"use client";
import Image from "next/image";

import { Manrope } from "next/font/google";
import "@/Styles/Homepage/payglocalHomepage.css"; //section 2 - is from homepage so i have to import the homepage style
import "@/Styles/Amazon/Amazon.css"; //section 2 - is from homepage so i have to import the homepage style

//navbar
import Logo from "@/Images/Amazon/payglocal-Logo.svg";

//local account section
import Usd from "@/Images/Mca/get-local-accounts-usd.svg";

//section 2 - accept pay-ins images
import CollectGlobalPayments from "@/Images/Homepage/collect-global-payments.png";
import CollectGlobalPaymentsMobile from "@/Images/Homepage/smart-payment-collection-mobile.png";
import ComplianceManagement from "@/Images/Homepage/compliance-management.png";
import TrackGetStatus from "@/Images/Homepage/track-get-status.png";
import SmartPaymentCollection from "@/Images/Homepage/smart-payment-collection.png";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import FAQ from "@/Components/FAQ";

//modal images
import ContactUsFormComponent from "@/Components/ContactUsFormComponent";
import HomepagePayInsGradientBoxes from "@/Components/SmallComponents/HomepagePayInsGradientBoxes";
import AmazonFooter from "../amazon/AmazonFooter";
import McaHeader from "./McaHeader";
import {
  getBase64EncodedCampaignDetails,
  handleCampaignRedirect,
} from "@/lib/utils";

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
});

function McaSection() {
  const [influencerId, setInfluencerId] = useState();
  let formSection = useRef();

  let router = useRouter();

  const [campaignDetails, setCampaignDetails] = useState(null);

  useEffect(() => {
    const encodedDetails = getBase64EncodedCampaignDetails();
    setCampaignDetails(encodedDetails);
  }, []);

  useEffect(() => {
    if (window?.location?.pathname.includes("/inf/")) {
      const id = window?.location?.pathname.split("/")[2];
      setInfluencerId(id);
    }
  }, []);

  const redirectToSignup = () => {
    handleCampaignRedirect(campaignDetails, influencerId);
  };

  //when someone click on navbar talk to our team button this function will scroll to the bottom form section
  function handleContactToTeamBtn() {
    formSection.current.scrollIntoView({ behavior: "smooth" });
  }

  let FAQData = [
    {
      question:
        "What is the difference between PayGlocal's multi-currency account and traditional bank accounts?",
      answer:
        "PayGlocal's multi-currency account enables you to accept payments like a local entity in the markets of interest. This allows for faster settlements and less conversion costs when compared to traditional bank accounts.",
    },
    {
      question: "Is this a global account or a local account?",
      answer:
        "PayGlocal’s multi-currency account set up gives you access to a global SWIFT account to process 33+ currencies as well as local currency accounts in four major geographies (United States, Canada, United Kingdom and European Union).",
    },
    {
      question: "What are the currencies supported for me to collect payments?",
      answer:
        "PayGlocal supports 33+ currencies through the global SWIFT account and 4 major currencies (USD, EUR, CAD and GBP) through local accounts for payment collection by Indian merchants.",
    },
    {
      question:
        "What is the timeline in which I will receive the payment to my Indian Bank account?",
      answer:
        "Once the payment is made into your multi-currency account and the supporting documents have been submitted by you with-in the stipulated time, it takes two to three working days for you to access funds in your Indian bank account.",
    },
    {
      question: "Does PayGlocal provide FIRC?",
      answer:
        "Yes, PayGlocal provides eFIRA/FIRC as generated by the partner banks once the amount is settled.",
    },
    {
      question: "How long can I hold the money in the multi-currency account?",
      answer:
        "PayGlocal’s multi-currency account product is not used to hold money. Once your multi-currency account receives money, you must submit supporting documents to get the settlement with-in two working days. If the documents are not submitted, the money goes back to the sender automatically.",
    },
    {
      question: "How do I track the transaction status?",
      answer:
        "You can check the status of your funds on the PayGlocal dashboard. You are also notified via email once the funds are transferred to your multi-currency account and settled into your Indian bank account to provide complete visibility into the process.",
    },
    {
      question: "What are payment rails and how does it matter?",
      answer:
        "Payment rails are the infrastructure that supports different payment transfers. If the wrong payment rails are used during fund transfers, the payment is automatically reverted to the customer. Always use the guided account details for sharing with your fund senders to ensure they are received in the safest and fastest mode possible.",
    },
    {
      question:
        "Are cash and cheque payments supported through multi-currency account?",
      answer:
        "No, multi-currency accounts can only support online bank transfers it doesn't support cash, cheque payments.",
    },
  ];

  return (
    <>
      <McaHeader redirectToSignup={redirectToSignup} manrope={manrope} />

      {/* fixed navbar */}
      <nav className="flex justify-between items-center background-custom-white w-full fixed px-4 sm:px-10 py-5 z-10 top-0 left-0">
        <Image
          src={Logo}
          width={224}
          height={40}
          alt="img"
          quality={100}
          className="market-payglocal-logo cursor-pointer"
          onClick={() => {
            router.push("/");
          }}
        />
        <button
          className={
            "background-custom-blue1 py-2.5 px-6 common-btn-text custom-text-white rounded-3xl sign-up-blue-btn-drop-shadow hover:scale-110 duration-300 "
          }
          onClick={handleContactToTeamBtn}
        >
          Talk to our team
        </button>
      </nav>

      {/* section 1 - local account section  */}
      <section className="flex justify-center items-center px-4 py-20 sm:px-10 relative overflow-hidden">
        <div className="flex flex-col-reverse lg:flex-row items-center  gap-6 lg:gap-20 ">
          <Image
            src={Usd}
            width={556}
            height={500}
            quality={100}
            alt="img"
            className=""
          />
          <div className="flex flex-col  gap-5 sm:gap-4 max-w-sm lg:max-w-[440px] w-full ">
            <h3 className="common-h3-heading text-center lg:text-left ">
              Get Local Accounts for global payments
            </h3>
            <p
              className={
                "common-body1-text custom-text-grey800 max-w-sm w-full text-center lg:text-left "
              }
            >
              Collect payments locally in USD, GBP, EUR and CAD via efficient
              and direct bank transfers.
            </p>
            <p
              className={
                "common-body1-text custom-text-grey800 max-w-sm w-full text-center lg:text-left "
              }
            >
              Ditch the high cost wire transfers
            </p>
          </div>
        </div>
      </section>

      {/* section 2 - feature grid section */}
      <section className="flex flex-col gap-14 py-20 px-4 sm:px-10  justify-center items-center">
        <div className="flex flex-col gap-4 justify-center items-center home-section2-access-pay-container">
          <h2 className="common-h2-heading  text-center custom-text-black home-section2-title ">
            PayGlocal offers features tailored for your dynamic business
          </h2>
        </div>

        <div className="home-section2-grid-parent-container">
          <div className="background-custom-grey50 flex flex-col lg:flex-row items-center gap-6 justify-between lg:items-start p-12 rounded-3xl">
            <div className="flex flex-col gap-2 ">
              <h5 className="common-h5-heading  custom-text-black text-center lg:text-left ">
                Get transparent pricing
              </h5>
              <p
                className={
                  "common-body2-text custom-text-grey600  pay-only-transaction-para  text-center lg:text-left w-full "
                }
              >
                Enjoy clear pricing and standard rates without any markup or
                hidden charges.
              </p>
            </div>
            <div className="flex flex-col sm:flex-row gap-2.5 lg:gap-1 overflow-hidden">
              <HomepagePayInsGradientBoxes title={"Markup Fees"} price="0%" />
              <HomepagePayInsGradientBoxes
                title={"Hidden Charges"}
                price="0%"
              />
              <HomepagePayInsGradientBoxes
                title={"Maintenance Charges"}
                price="0%"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 xl:grid-cols-2  pt-2.5 box-border home-section2-grid-container gap-2.5">
            <div className="pt-10 sm:pt-12 pl-4 sm:pl-14 lg:pl-12 pr-4 sm:pr-14 lg:pr-12 pb-10 sm:pb-12 flex flex-col justify-center lg:justify-start  gap-4 sm:gap-10 rounded-3xl background-custom-grey50 collect-global-payments-container xl:relative overflow-hidden col-start-1 col-end-2 lg:row-start-1 lg:row-end-3">
              <div className="flex flex-col justify-center lg:justify-start gap-2 collect-global-payments-title-para-container ">
                <h5 className="common-h5-heading custom-text-black  text-center lg:text-start ">
                  Collect global payments
                </h5>
                <p
                  className={
                    "common-body2-text custom-text-grey600  text-center lg:text-start collect-global-para "
                  }
                >
                  Collect payments locally in USD, GBP, EUR, and CAD, and
                  globally in 33 currencies from 180+ countries via a global
                  currency account.
                </p>
              </div>
              <Image
                src={CollectGlobalPayments}
                width={462}
                height={260}
                quality={100}
                alt="img"
                className=" xl:absolute xl:bottom-14 xl:right-16 hidden sm:block"
              />
              <Image
                src={CollectGlobalPaymentsMobile}
                width={271}
                height={314}
                quality={100}
                alt="img"
                className=" xl:absolute xl:bottom-14 xl:right-16 block sm:hidden"
              />
            </div>

            <div className="pt-10 sm:pt-12 pl-4 sm:pl-14 lg:pl-12 pr-4 sm:pr-14 lg:pr-12 pb-10 sm:pb-12 flex flex-col  justify-center lg:justify-start  gap-4 sm:gap-10 rounded-3xl background-custom-grey50 compliance-management-container  xl:relative overflow-hidden">
              <div className="flex flex-col justify-center lg:justify-start gap-2 effortless-compliance-management-title-para-container">
                <h5 className="common-h5-heading custom-text-black  text-center lg:text-start ">
                  Effortless compliance management
                </h5>
                <p
                  className={
                    "common-body2-text custom-text-grey600  collect-global-para  text-center lg:text-start "
                  }
                >
                  Receive FIRC right in your inbox after settlement, and stay
                  compliant!
                </p>
              </div>
              <Image
                src={ComplianceManagement}
                width={238}
                height={247}
                quality={100}
                alt="img"
                className=" xl:absolute xl:bottom-4  xl:right-10"
              />
            </div>

            <div className="pt-10 sm:pt-12 pl-4 sm:pl-14 lg:pl-12 pr-4 sm:pr-14 lg:pr-12 pb-10 sm:pb-12  flex flex-col  justify-center lg:justify-start  gap-4 sm:gap-10 rounded-3xl background-custom-grey50 track-get-status-container xl:relative overflow-hidden col-start-1 col-end-2">
              <div className="flex flex-col justify-center lg:justify-start gap-2  track-and-get-status-container ">
                <h5 className="common-h5-heading custom-text-black  text-center lg:text-start ">
                  Track and get status
                </h5>
                <p
                  className={
                    "common-body2-text custom-text-grey600  collect-global-payments-para  text-center lg:text-start "
                  }
                >
                  Stay informed with frequent notifications on your fund status
                  every step of the way.
                </p>
              </div>
              <Image
                src={TrackGetStatus}
                width={562}
                height={215}
                quality={100}
                alt="img"
                className=" xl:absolute xl:bottom-6  xl:right-0 track-and-get-status-img"
              />
            </div>

            <div className="pt-10 pb-0 sm:pt-12 pl-4 sm:pl-14 lg:pl-12 pr-4 sm:pr-14 lg:pr-12  xl:pb-12   flex flex-col  justify-center lg:justify-start  gap-4 lg:gap-10 rounded-3xl background-custom-grey50 smart-payment-collection-container   xl:relative overflow-hidden lg:row-start-2 lg:row-end-4">
              <div className="flex flex-col justify-center lg:justify-start gap-2 smart-payment-collection-title-para-container ">
                <h5 className="common-h5-heading custom-text-black  text-center lg:text-start ">
                  Smart payment collection
                </h5>
                <p
                  className={
                    "common-body2-text custom-text-grey600   text-center lg:text-start "
                  }
                >
                  Manage multi-currency transactions easily with transparent
                  pricing, instant notifications, and downloadable FIRA from the
                  dashboard.
                </p>
              </div>
              <Image
                src={SmartPaymentCollection}
                width={453}
                height={298}
                quality={100}
                alt="img"
                className="xl:absolute xl:bottom-0  xl:-right-10"
              />
            </div>
          </div>
        </div>
        <div className="text-center">
          <button
            onClick={redirectToSignup}
            className={
              "background-custom-blue1 py-2.5 px-6 common-btn-text custom-text-white rounded-3xl sign-up-blue-btn-drop-shadow hover:scale-110 duration-300 " +
              manrope.className
            }
          >
            Sign Up here
          </button>
        </div>
      </section>

      {/* section - 1 form section */}
      <section
        className="flex flex-col gap-14 py-20 px-4 sm:px-10  justify-center items-center background-custom-grey50"
        ref={formSection}
      >
        <div className="flex flex-col lg:flex-row gap-10 lg:gap-20 items-center lg:items-start">
          <div className="flex flex-col gap-4">
            <div className="flex flex-col gap-2 5">
              <h3 className="common-h3-heading text-center lg:text-left">
                Easy. Fast. Smooth.
              </h3>
              <h5 className="common-h5-heading custom-text-blue1 text-center lg:text-left">
                Everything your global business deserves!
              </h5>
            </div>
            <p className="custom-text-grey600 common-body1-text lg:max-w-64 text-center lg:text-left">
              Help us with your details and we will connect with you ASAP!
            </p>
          </div>

          <ContactUsFormComponent
            modalPresent={true}
            talkToOurTeamBtnView={true}
            source="MCA Landing"
            campaignDetails={campaignDetails}
            influencerId={influencerId}
          />
        </div>
      </section>

      {/* FAQ  */}
      <FAQ FAQData={FAQData} />

      {/* amazon footer  */}
      <AmazonFooter functionClick={handleContactToTeamBtn} />
    </>
  );
}

export default McaSection;
