export const blogs = {
  "swift-charges-explained": {
    img: "/blogs/swift-charges-explained/banner.png",
    thumbnail: "/blogs/swift-charges-explained/header.png",
    name: "PayGlocal Team",
    date: "13 December 2024",
    readMins: "4",
    heading: "SWIFT Transfer Fees and Charges Explained",
    preface: "This blog covers different types of SWIFT charges, their cost structure, factors influencing and ways to minimize delays with alternative solutions.",
    src: "/blog/swift-charges-explained",
    tag: "Business",
  },
  "what-is-foreign-exchange": {
    img: "/blogs/what-is-foreign-exchange/banner.png",
    thumbnail: "/blogs/what-is-foreign-exchange/header.png",
    name: "PayGlocal Team",
    date: "06 December 2024",
    readMins: "4",
    heading: "What Is Foreign Exchange And How It Works? ",
    preface: "Learn what a foreign exchange rate is, and how it works. Explore the top factors that affect foreign exchange and the different types of currency systems.",
    src: "/blog/what-is-foreign-exchange",
    tag: "Business",
  },
  "how-to-get-international-clients-for-web-development-tips": {
    img: "/blogs/how-to-get-international-clients-for-web-development-tips/banner.png",
    thumbnail: "/blogs/how-to-get-international-clients-for-web-development-tips/header.png",
    name: "PayGlocal Team",
    date: "04 December 2024",
    readMins: "4",
    heading: "Smart Strategies To Gain International Web Development Clients ",
    preface: "Understand your target market, specialize in a high-demand niche, and optimize your online presence to get international clients for web development.",
    src: "/blog/how-to-get-international-clients-for-web-development-tips",
    tag: "Business",
  },
  "swift-transfer-time-explained": {
    img: "/blogs/swift-transfer-time-explained/banner.png",
    thumbnail: "/blogs/swift-transfer-time-explained/header.png",
    name: "PayGlocal Team",
    date: "02 December 2024",
    readMins: "4",
    heading: "Understanding How Long SWIFT Transfers Take",
    preface: "Discover how the expected SWIFT transfer time: typically 1 to 5 working days, is influenced by intermediary banks, time zones and cut-off times.",
    src: "/blog/swift-transfer-time-explained",
    tag: "Business",
  },
  "top-10-products-export-India-2024": {
    img: "/blogs/top-10-products-export-India-2024/banner.png",
    thumbnail: "/blogs/top-10-products-export-India-2024/header.png",
    name: "PayGlocal Team",
    date: "29 November 2024",
    readMins: "8",
    heading: "Top 10 Products Exported from India in 2024",
    preface: "Discover the top 10 products exported from India: Petroleum, Gems, Pharmaceuticals, Fabric, Chemicals, Machines, Metals, Automobiles, Dairy, and Tea.",
    src: "/blog/top-10-products-export-India-2024",
    tag: "Business",
  },
  "rcmc-full-form-registration-documents": {
    img: "/blogs/rcmc-full-form-registration-documents/banner.png",
    thumbnail: "/blogs/rcmc-full-form-registration-documents/header.png",
    name: "PayGlocal Team",
    date: "28 November 2024",
    readMins: "4",
    heading: "Understanding RCMC Registration, Benefits, and Document Requirements in India",
    preface: "Learn about RCMC registration in India, its benefits, and required documents. Discover how RCMC can boost your export business effectively! ",
    src: "/blog/rcmc-full-form-registration-documents",
    tag: "Business",
  },
  "receivable-accounting-definition-types": {
    img: "/blogs/receivable-accounting-definition-types/banner.png",
    thumbnail: "/blogs/receivable-accounting-definition-types/header.png",
    name: "PayGlocal Team",
    date: "26 November 2024",
    readMins: "6",
    heading: "Understanding Accounts Receivable in Accounting: Definition, Uses and Types",
    preface: "Discover Accounts Receivable, a crucial asset, and how AR impacts business cash flow and can be used as collateral for business loans.",
    src: "/blog/receivable-accounting-definition-types",
    tag: "Business",
  },
  "import-export-documentation-required": {
    img: "/blogs/import-export-documentation-required/banner.png",
    thumbnail: "/blogs/import-export-documentation-required/header.png",
    name: "PayGlocal Team",
    date: "25 November 2024",
    readMins: "4",
    heading: "Common Documents Required for Import and Export Procedures ",
    preface: "Discover why import-export documentation is mandatory for all import and export transactions and is primary for starting any business activities. ",
    src: "/blog/import-export-documentation-required",
    tag: "Business",
  },
  "forms-of-export-finance-business-growth": {
    img: "/blogs/forms-of-export-finance-business-growth/banner.png",
    thumbnail: "/blogs/forms-of-export-finance-business-growth/header.png",
    name: "PayGlocal Team",
    date: "21 November 2024",
    readMins: "4",
    heading: "Types and Uses of Export Finance in Business Growth ",
    preface: "Discover insights on export finance, their types, how they support working capital and mitigate risks to aid your business growth.",
    src: "/blog/forms-of-export-finance-business-growth",
    tag: "Business",
  },
  "how-to-learn-export-documentation-strategy": {
    img: "/blogs/how-to-learn-export-documentation-strategy/banner.png",
    thumbnail: "/blogs/how-to-learn-export-documentation-strategy/header.png",
    name: "PayGlocal Team",
    date: "19 November 2024",
    readMins: "8",
    heading: "Guide to Learning Export Procedures and Documentation",
    preface: "Discover various documents required for an export license in India, different export procedures, and banking options for international transactions.",
    src: "/blog/how-to-learn-export-documentation-strategy",
    tag: "Business",
  },
  "proforma-invoice-in-export-creation": {
    img: "/blogs/proforma-invoice-in-export-creation/banner.png",
    thumbnail: "/blogs/proforma-invoice-in-export-creation/header.png",
    name: "PayGlocal Team",
    date: "13 November 2024",
    readMins: "8",
    heading: "Creating a Proforma Invoice for Export Sales ",
    preface: "Proforma invoices in export are comprehensive quotations used pre-shipment, serving as transaction previews to prevent misunderstandings and aid planning.",
    src: "/blog/proforma-invoice-in-export-creation",
    tag: "Business",
  },
  "fob-full-form-export-invoices": {
    img: "/blogs/fob-full-form-export-invoices/banner.png",
    thumbnail: "/blogs/fob-full-form-export-invoices/header1.png",
    name: "PayGlocal Team",
    date: "12 November 2024",
    readMins: "6",
    heading: "Understanding the Meaning and Use of FOB in Export Invoices",
    preface: "Learn FOB meaning in export invoices: Its role in shipping, cost allocation, risk transfer, and impact on international trade transactions.",
    src: "/blog/fob-full-form-export-invoices",
    tag: "Business",
  },
  "igst-cgst-sgst-indian-gst-types": {
    img: "/blogs/igst-cgst-sgst-indian-gst-types/banner.png",
    thumbnail: "/blogs/igst-cgst-sgst-indian-gst-types/header.png",
    name: "PayGlocal Team",
    date: "11 November 2024",
    readMins: "4",
    heading: "Understanding Types of GST: IGST, CGST, SGST, and UTGST in India",
    preface: "Learn about IGST, CGST, SGST - the types of GST in India and their relevance for interstate and intrastate transactions.",
    src: "/blog/igst-cgst-sgst-indian-gst-types",
    tag: "Business",
  },
  "export-payment-terms-understanding": {
    img: "/blogs/export-payment-terms-understanding/banner.png",
    thumbnail: "/blogs/export-payment-terms-understanding/header.png",
    name: "PayGlocal Team",
    date: "05 November 2024",
    readMins: "8",
    heading: "Understanding Types of Export Payment Terms",
    preface: "Understand the criticality of export payment terms, their selection in international trade, and techniques for handling transaction risks.",
    src: "/blog/export-payment-terms-understanding",
    tag: "Business",
  },
  "bank-guarantee-vs-letter-of-credit-differences": {
    img: "/blogs/bank-guarantee-vs-letter-of-credit-differences/banner.png",
    thumbnail: "/blogs/bank-guarantee-vs-letter-of-credit-differences/header.png",
    name: "PayGlocal Team",
    date: "28 October 2024",
    readMins: "4",
    heading: "Bank Guarantee vs. Letter of Credit: Understanding the Differences. ",
    preface: "Discover how a Bank guarantee and letters of credit help businesses safeguard financial interests and streamline transactions in trade. ",
    src: "/blog/bank-guarantee-vs-letter-of-credit-differences",
    tag: "Business",
  },
  "checking-aba-number-methods": {
    img: "/blogs/checking-aba-number-methods/banner.png",
    thumbnail: "/blogs/checking-aba-number-methods/header.png",
    name: "PayGlocal Team",
    date: "25 October 2024",
    readMins: "6",
    heading: "How to Find Your ABA Routing Number? ",
    preface: "Your ABA routing number is found on the bottom left corner of personal and business cheques or via banking platforms.",
    src: "/blog/checking-aba-number-methods",
    tag: "Business",
  },
  "sac-code-full-form-hsn-difference": {
    img: "/blogs/sac-code-full-form-hsn-difference/banner.png",
    thumbnail: "/blogs/sac-code-full-form-hsn-difference/header.png",
    name: "PayGlocal Team",
    date: "24 October 2024",
    readMins: "8",
    heading: "What are the Differences and Similarities between SAC Code and HSN Code? ",
    preface: "The blog compares both SAC (Service Accounting Code) and HSN (Harmonized System of Nomenclature Code) which are key elements in the GST system. ",
    src: "/blog/sac-code-full-form-hsn-difference",
    tag: "Business",
  },
  "iban-understanding-its-function": {
    img: "/blogs/iban-understanding-its-function/banner.png",
    thumbnail: "/blogs/iban-understanding-its-function/header.png",
    name: "PayGlocal Team",
    date: "23 October 2024",
    readMins: "8",
    heading: "Understanding What an International Bank Account Number (IBAN) Is and How It Works. ",
    preface: "IBAN stands for International Bank Account Number, a universally recognized identifier for bank accounts with a specific structure. ",
    src: "/blog/iban-understanding-its-function",
    tag: "Business",
  },
  "section-44ada-tax-scheme": {
    img: "/blogs/section-44ada-tax-scheme/banner.png",
    thumbnail: "/blogs/section-44ada-tax-scheme/header.png",
    name: "PayGlocal Team",
    date: "22 October 2024",
    readMins: "6",
    heading: "Section 44ADA - Presumptive Tax Scheme for Professionals ",
    preface: "Discover tax savings with Section 44ADA. Simplify tax filing by declaring 50% of your gross receipts as presumptive income to focus on business growth. ",
    src: "/blog/section-44ada-tax-scheme",
    tag: "Business",
  },
  "difference-between-neft-rtgs-guide": {
    img: "/blogs/difference-between-neft-rtgs-guide/banner.png",
    thumbnail: "/blogs/difference-between-neft-rtgs-guide/header.png",
    name: "PayGlocal Team",
    date: "16 October 2024",
    readMins: "4",
    heading: "Difference Between NEFT and RTGS: A Simple Guide ",
    preface: "Discover the difference between NEFT and RTGS payment systems: their purpose, pros and cons, processing time, charges, minimum and maximum limit.",
    src: "/blog/difference-between-neft-rtgs-guide",
    tag: "Business",
  },
  "mt103-swift-message-elements": {
    img: "/blogs/mt103-swift-message-elements/banner.png",
    thumbnail: "/blogs/mt103-swift-message-elements/header.png",
    name: "PayGlocal Team",
    date: "14 October 2024",
    readMins: "6",
    heading: "Understanding the Use and Elements of MT103 in SWIFT Payment Transfers",
    preface: "Discover how to use the MT103 SWIFT message in payment transfers effectively. Learn the essential elements and streamline your transactions today!",
    src: "/blog/mt103-swift-message-elements",
    tag: "Business",
  },
  "understanding-app-fraud-in-the-uk": {
    img: "/blogs/understanding-app-fraud-in-the-uk/banner.png",
    thumbnail: "/blogs/understanding-app-fraud-in-the-uk/header.png",
    name: "PayGlocal Team",
    date: "11 October 2024",
    readMins: "4",
    heading: "Understanding APP Fraud in the UK: A Growing Concern",
    preface: "Read more about APP fraud and the changing regulatory landscape in the UK, this blog highlights the nuances and applicability of regulation.",
    src: "/blog/understanding-app-fraud-in-the-uk",
    tag: "Business",
  },
  "how-to-select-amazon-global-in-india-explained": {
    img: "/blogs/how-to-select-amazon-global-in-india-explained/banner.png",
    thumbnail: "/blogs/how-to-select-amazon-global-in-india-explained/header.png",
    name: "PayGlocal Team",
    date: "9 October 2024",
    readMins: "8",
    heading: "Sell and Ship Products Internationally from India using Amazon Global ",
    preface: "Learn how to select Amazon Global in India for your products, understanding Amazon’s global marketplace requirements for international business expansion. ",
    src: "/blog/how-to-select-amazon-global-in-india-explained",
    tag: "Business",
  },
  "international-transaction-fees-explained": {
    img: "/blogs/international-transaction-fees-explained/banner.png",
    thumbnail: "/blogs/international-transaction-fees-explained/header.png",
    name: "PayGlocal Team",
    date: "7 October 2024",
    readMins: "4",
    heading: "Understanding International Transaction Fees: How Businesses Can Thrive Globally? ",
    preface: "Understanding why international transaction fees is key to protecting your business profits and avoiding unnecessary charges during global trade.",
    src: "/blog/international-transaction-fees-explained",
    tag: "Business",
  },
  "is-ifsc-and-swift-code-same-difference": {
    img: "/blogs/is-ifsc-and-swift-code-same-difference/banner.png",
    thumbnail: "/blogs/is-ifsc-and-swift-code-same-difference/header.png",
    name: "PayGlocal Team",
    date: "3 October 2024",
    readMins: "4",
    heading: "Difference Between Swift Code and IFSC Code for Transactions",
    preface: "The blog explains the difference between ifsc and swift code, how they serve distinct purposes in the global banking system.",
    src: "/blog/is-ifsc-and-swift-code-same-difference",
    tag: "Business",
  },
  "gst-on-export-of-services-impact": {
    img: "/blogs/gst-on-export-of-services-impact/banner.png",
    thumbnail: "/blogs/gst-on-export-of-services-impact/header.png",
    name: "PayGlocal Team",
    date: "1 October 2024",
    readMins: "8",
    heading: "Impact of GST on Export of Services in India",
    preface: "No GST is levied on the export of any services. The treatment is considered as zero-rated supply in India offering competitiveness.",
    src: "/blog/gst-on-export-of-services-impact",
    tag: "Business",
  },
  "sort-code-understanding-usage": {
    img: "/blogs/sort-code-understanding-usage/banner.png",
    thumbnail: "/blogs/sort-code-understanding-usage/header.png",
    name: "PayGlocal Team",
    date: "30 September 2024",
    readMins: "4",
    heading: "Understanding What a Sort Code Is and How to Use It",
    preface: "A sort code is a 6-digit number used to identify UK banks and branches. It ensures accurate and efficient payment routing.",
    src: "/blog/sort-code-understanding-usage",
    tag: "Business",
  },
  "amazon-fulfillment-fees-changes": {
    img: "/blogs/amazon-fulfillment-fees-changes/banner.png",
    thumbnail: "/blogs/amazon-fulfillment-fees-changes/header.png",
    name: "PayGlocal Team",
    date: "24 September 2024",
    readMins: "12",
    heading: "Amazon FBA Fees: What You Should Know ",
    preface: "Get updated about the specific 2024 Amazon fulfillment fees, including changes to fulfillment, referral, and storage fees.",
    src: "/blog/amazon-fulfillment-fees-changes",
    tag: "Business",
  },
  "role-and-importance-of-selecting-C&F-Agent": {
    img: "/blogs/role-and-importance-of-selecting-C&F-Agent/banner.png",
    thumbnail: "/blogs/role-and-importance-of-selecting-C&F-Agent/header.png",
    name: "PayGlocal Team",
    date: "20 September 2024",
    readMins: "4",
    heading: "Role and Importance of Selecting the Right C&F Agent ",
    preface: "A C&F agent assists in customs clearance, coordinates with carriers, handles shipping and ensures cost-effectiveness.",
    src: "/blog/role-and-importance-of-selecting-C&F-Agent",
    tag: "Business",
  },
  "managing-and-understanding-your-EEFC": {
    img: "/blogs/managing-and-understanding-your-EEFC/banner.png",
    thumbnail: "/blogs/managing-and-understanding-your-EEFC/header.png",
    name: "PayGlocal Team",
    date: "19 September 2024",
    readMins: "8",
    heading: "Managing and Understanding Your EEFC Account",
    preface: "Learn the full form of EEFC account, its primary purpose, and how it supports foreign exchange-earners.",
    src: "/blog/managing-and-understanding-your-EEFC",
    tag: "Business",
  },
  "top-10-freelancing-sites-2024": {
    img: "/blogs/top-10-freelancing-sites-2024/banner.png",
    thumbnail: "/blogs/top-10-freelancing-sites-2024/header.png",
    name: "PayGlocal Team",
    date: "12 September 2024",
    readMins: "12",
    heading: "Top 10 Freelancing Websites for Online Work (2024)",
    preface:
      "Discover the top 10 freelancing sites for finding online work in 2024, including Upwork, Fiverr, Toptal, Freelancer.com, and more.",
    src: "/blog/top-10-freelancing-sites-2024",
    tag: "Business",
  },
  "edpms-understanding-system": {
    img: "/blogs/edpms-understanding-system/banner.png",
    thumbnail: "/blogs/edpms-understanding-system/header.png",
    name: "PayGlocal Team",
    date: "10 September 2024",
    readMins: "9",
    heading:
      "Understanding the Export Data Processing and Monitoring System (EDPMS)",
    preface:
      "EDPMS, launched by the Reserve Bank of India, enhances transparency in dollar transactions and aids in managing Forex operations.",
    src: "/blog/edpms-understanding-system",
    tag: "Business",
  },

  "payment-transaction-processing-types": {
    img: "/blogs/payment-transaction-processing-types/banner.png",
    thumbnail: "/blogs/payment-transaction-processing-types/header.png",
    name: "PayGlocal Team",
    date: "09 September 2024",
    readMins: "7",
    heading: "Understanding Payment Transaction Processing and Types",
    preface:
      "Understanding payment transaction processing, from authorization to clearing, is crucial for businesses to ensure smooth and secure transactions in today's digital economy.",
    src: "/blog/payment-transaction-processing-types",
    tag: "Payments",
  },

  "iec-code-import-export ": {
    img: "/blogs/iec-code-import-export/banner.png",
    thumbnail: "/blogs/iec-code-import-export/header.png",
    name: "PayGlocal Team",
    date: "05 September 2024",
    readMins: "7",
    heading:
      "Applying for IEC (Import Export Code): Benefits and How to Get It",
    preface:
      "The Import Export Code (IEC) is crucial for international trade, mandated for customs clearance and legal compliance in global transactions.",
    src: "/blog/iec-code-import-export",
    tag: "Business",
  },
  "itr-for-freelancers-guide ": {
    img: "/blogs/itr-for-freelancers-guide/banner.png",
    thumbnail: "/blogs/itr-for-freelancers-guide/header.png",
    name: "PayGlocal Team",
    date: "04 September 2024",
    readMins: "11",
    heading: "How to file Income Tax Returns (ITR) for freelancers in India",
    preface:
      "Understand how to file ITR for freelancers in India, including applicable rates, deductions, and filing process via ITR-3 and ITR-4 forms.",
    src: "/blog/itr-for-freelancers-guide",
    tag: "Business",
  },
  "brc-details-download-print ": {
    img: "/blogs/brc-details-download-print/banner.png",
    thumbnail: "/blogs/brc-details-download-print/header.png",
    name: "PayGlocal Team",
    date: "30 August 2024",
    readMins: "7",
    heading: "Understanding How to Download and Print e-BRC Certificate Online",
    preface:
      "Get step-by-step guide on how to download and print e-BRC from the DGFT website and troubleshoot common issues involved in accessing BRC details.",
    src: "/blog/brc-details-download-print",
    tag: "Business",
  },
  "how-to-get-clients-for-web-development-strategies ": {
    img: "/blogs/how-to-get-clients-for-web-development-strategies/banner.png",
    thumbnail:
      "/blogs/how-to-get-clients-for-web-development-strategies/header.png",
    name: "PayGlocal Team",
    date: "22 August 2024",
    readMins: "8",
    heading:
      "How to Get Clients for Web Development: Proven Strategies and Tips ",
    preface:
      "Learn proven strategies and tips on how to get clients for web development using social media, and employing effective content marketing strategies.",
    src: "/blog/how-to-get-clients-for-web-development-strategies",
    tag: "Business",
  },
  "lut-certificate-download-furnish": {
    img: "/blogs/lut-certificate-download-furnish/header3.png",
    thumbnail: "/blogs/lut-certificate-download-furnish/feature5.png",
    name: "PayGlocal Team",
    date: "14 August 2024",
    readMins: "8",
    heading: "LUT Certificate: How to Download and Furnish on GST Portal",
    preface:
      "Learn the steps to download and furnish a LUT certificate on the GST portal, ensuring GST obligations are fulfilled.",
    src: "/blog/lut-certificate-download-furnish",
    tag: "Business",
  },
  "comprehensive-guide-to-fraud-reporting-mitigation-strategies": {
    img: "/blogs/comprehensive-guide-to-fraud-reporting-mitigation-strategies/header.png",
    thumbnail:
      "/blogs/comprehensive-guide-to-fraud-reporting-mitigation-strategies/featured.png",
    name: "Rohit Sukhija, Mansi Gundale",
    date: "30 July 2024",
    readMins: "5",
    heading: "Comprehensive Guide to Fraud Reporting and Mitigation Strategies",
    preface:
      "Fraud reporting is a critical process in maintaining financial integrity and combating fraudulent activities. When a consumer reports a suspicious transaction to their issuer, it alerts the bank to potential fraud. Dive in to our latest blog for insights and strategies to prevent fraud. ",
    src: "/blog/comprehensive-guide-to-fraud-reporting-mitigation-strategies",
    tag: "Business",
  },
  "understanding-chargeback-fraud": {
    img: "/blogs/understanding-chargeback-fraud/header.png",
    thumbnail: "/blogs/understanding-chargeback-fraud/featured.png",
    name: "Rohit Sukhija, Mansi Gundale",
    date: "12 July 2024",
    readMins: "5",
    heading:
      "Understanding Chargeback Fraud: Insights and Prevention Strategies",
    preface:
      "In our last blog, we touched upon the concept of Liability Shift in card payments. We took a closer look at the various types of liability shifts and how choosing the right payment service provider can shield you from potential risks. This blog delves into the intricacies of fraud chargebacks and effective prevention strategies.",
    src: "/blog/understanding-chargeback-fraud",
    tag: "Business",
  },
  "stay-ahead-of-fraud-liability-shift": {
    img: "/blogs/stay-ahead-of-fraud-liability-shift/header.png",
    thumbnail: "/blogs/stay-ahead-of-fraud-liability-shift/featured.png",
    name: "Rohit Sukhija, Mansi Gundale",
    date: "17 June 2024",
    readMins: "4",
    heading:
      "Stay Ahead of Fraud: Understanding Liability Shift in Card Payments",
    preface:
      "At PayGlocal, we help our clients to stay ahead in this precarious world of online payments fraud. In the fast-paced world of digital transactions, staying one step ahead of fraudsters is crucial for any business. This article is one of the first articles where we dig deeper into the concept of online card payment fraud and related concepts.",
    src: "/blog/stay-ahead-of-fraud-liability-shift",
    tag: "Business",
  },
  "e-invoicing-under-GST": {
    img: "/blogs/e-invoicing-under-GST/header.png",
    thumbnail: "/blogs/e-invoicing-under-GST/featured.png",
    name: "Akshay Hingmire",
    date: "6 June 2024",
    readMins: "7",
    heading: "E-Invoicing Under GST: Everything You Need to Know",
    preface:
      "Navigating the world of business finance can often be a labyrinth of paperwork, regulations, and compliance headaches. But with the advent of e-invoicing under the Goods and Services Tax (GST) in India, businesses can now streamline their invoicing processes like never before. This blog covers everything you need to know about GST e-invoicing, how it works, and the benefits it offers.",
    src: "/blog/e-invoicing-under-GST",
    tag: "Business",
  },
  "mastering-exports-LUT": {
    img: "/blogs/mastering-exports-LUT/header.png",
    thumbnail: "/blogs/mastering-exports-LUT/featured.png",
    name: "Akshay Hingmire",
    date: "23 May 2024",
    readMins: "4",
    heading:
      "Mastering Exports: A Complete Guide to Letters of Undertaking (LUT) for Indian Exporters",
    preface:
      "Navigating the complexities of international trade can be challenging, but understanding and utilizing a Letter of Undertaking (LUT) under the GST regime can significantly ease the process for Indian exporters. This comprehensive guide explores the benefits and everything you need to know about LUT.",
    src: "/blog/mastering-exports-LUT",
    tag: "Business",
  },
  "choosing-the-right-payment-gateway": {
    img: "/blogs/choosing-the-right-payment-gateway/header.png",
    thumbnail: "/blogs/choosing-the-right-payment-gateway/featured.png",
    name: "Mansi",
    date: "10 May 2024",
    readMins: "4",
    heading: "Choosing the Right Payment Gateway",
    preface:
      "Explore the strategic importance of selecting the right payment gateway to enhance your international customer experience. Delve into the necessity of customizing payment systems to match cultural preferences, ensure robust security, and support regional payment methods. Gain insights into implementing consistent branding, legal compliance, and effective localization strategies. Learn how PayGlocal’s payment solutions ensure smooth and secure transactions.",
    src: "/blog/choosing-the-right-payment-gateway",
    tag: "Payments",
  },
  HSN_Codes: {
    img: "/blogs/HSN_Codes/header.png",
    thumbnail: "/blogs/HSN_Codes/feature.png",
    name: "Rishabh K",
    date: "5 Apr 2024",
    heading: "Cracking the Code: HSN Simplified",
    preface:
      "Explore the importance of HSN (Harmonized System of Nomenclature) codes in global trade. Understand their role in standardizing product classification, simplifying tax calculation, and ensuring regulatory compliance. Learn how HSN codes streamline business operations and facilitate international commerce.",
    src: "/blog/HSN_Codes",
    tag: "Business",
  },
  Freelancer_ind: {
    img: "/blogs/freelancer-india/banner.png",
    thumbnail: "/blogs/freelancer-india/feature.png",
    name: "Parvathi",
    date: "26 March 2024",
    heading: "Freelancing from India - A Growing Opportunity",
    preface:
      "India's freelance economy thrives with over 15 million professionals across IT, content creation, design, and digital marketing. Platforms like Upwork connect them to global clients. Success entails specialization, strong online presence, networking, delivering quality work on time, and staying updated with industry trends. Embracing freelancing offers a lucrative career path for Indian professionals in various domains.",
    src: "/blog/freelancer-india",
    tag: "Business",
  },
  "Alt-id": {
    img: "/blogs/alt-id/header.png",
    thumbnail: "/blogs/alt-id/feature.png",
    name: "Monica Singh, Akhil Sukumaran",
    date: "13 March 2024",
    heading: "Alt ID Solution for Guest Checkout Transactions",
    preface:
      "Explore Alt IDs, the innovative solution for enhanced online transaction security. By leveraging Alt IDs, merchants can ensure that transactions are conducted securely and adhere to regulatory requirements, ensuring a safer online shopping experience for all.",
    src: "/blog/alt-id",
    tag: "Payments",
  },
  "RoSCTL-Textile-Export": {
    img: "/blogs/RoSCTL/header.png",
    thumbnail: "/blogs/RoSCTL/feature.png",
    name: "Rishabh K",
    date: "9 Feb 2024",
    heading: "Empowering Textile Exports – The RoSCTL Scheme",
    preface:
      "Unlocking competitiveness for India's apparel export industry, RoSCTL offers refunds on state and central taxes. Learn how this initiative fosters growth and dynamism in the textile sector, promoting global competitiveness and market expansion. Discover the benefits, restrictions, and advantages of the RoSCTL scheme in shaping India's position in the global textile and apparel market.",
    src: "/blog/RoSCTL-Textile-Export",
    tag: "Business",
  },
  nostroVostro: {
    img: "/blogs/nostro-vostro/header.png",
    thumbnail: "/blogs/nostro-vostro/featured.png",
    name: "Akhil Sukumaran",
    date: "25 Jan 2024",
    heading: "Understanding Nostro and Vostro accounts",
    preface:
      "Explore Nostro and Vostro accounts in international banking. Learn their functions, benefits, and how they simplify cross-border transactions.",
    src: "/blog/nostro-vostro",
    tag: "Payments",
  },
  softex: {
    img: "/blogs/softex/h2.png",
    thumbnail: "/blogs/softex/f2.png",
    name: "Parvathi Nair",
    date: "19 Jan 2024",
    heading: "SOFTEX: A comprehensive guide",
    preface:
      "Explore the vital role of Softex certification in India's software export industry. Learn how this RBI-mandated process ensures regulatory compliance, mitigates financial risks, and fosters transparent, accountable global transactions for software companies. Prioritize Softex for seamless growth, international credibility, and sustained success in the dynamic landscape of software export.",
    src: "/blog/softex",
    tag: "Payments",
  },
  "ACH-payments": {
    img: "/blogs/ach-payments/h1.png",
    thumbnail: "/blogs/ach-payments/f1.png",
    name: "Rishabh K",
    date: "10 Jan 2024",
    heading: "Understanding ACH payments",
    preface:
      "Explore the speed and convenience of ACH payments – the backbone of electronic fund transfers in the US. Cost-effective, secure, and evolving for faster transactions for businesses and individuals.",
    src: "/blog/ach-payments",
    tag: "Payments",
  },
  "xpress-shopify": {
    img: "/blogs/xpress-shopify/header.png",
    thumbnail: "/blogs/xpress-shopify/feature.png",
    name: "Ninad Ajnikar",
    date: "27 Dec 2023",
    heading: "Introducing Xpress PayFlow for Shopify",
    preface:
      "Discover how PayGlocal's Xpress PayFlow on Shopify can provide a seamless, one-click checkout experience for global merchants. Boost sales and enhance customer experience effortlessly.",
    src: "/blog/xpress-payflow-shopify",
    tag: "Business",
  },
  "forex-management": {
    img: "/blogs/forex-management/header1.png",
    thumbnail: "/blogs/forex-management/feature.png",
    name: "Parvathi Nair",
    date: "15 Dec 2023",
    heading: "Optimizing Forex Management: A Deep Dive into EEFC Accounts",
    preface:
      "Explore the world of efficient foreign exchange management with insights into Exchange Earners' Foreign Currency (EEFC) accounts. Uncover the benefits, limitations, and alternative solutions for exporters navigating the complexities of international trade. Discover strategic financial tools to enhance stability and growth in the global market.",
    src: "/blog/eefc",
    tag: "Business",
  },
  "import-export-codes": {
    img: "/blogs/import-export-codes/header.png",
    thumbnail: "/blogs/import-export-codes/featured.png",
    name: "Akhil Sukumaran",
    date: "7 Dec 2023",
    heading:
      "Understanding Import-Export Codes (IEC) for Indian Importers and Exporters",
    preface:
      "Unlock international markets seamlessly with the Importer Exporter Code (IEC)! Explore its pivotal role in streamlining trade, securing licenses, and accessing benefits for Indian businesses.",
    src: "/blog/import-export-codes",
    tag: "Business",
  },
  "significance-of-brc": {
    img: "/blogs/significance-of-brc/header2.png",
    thumbnail: "/blogs/significance-of-brc/featured2.png",
    name: "Parvathi Nair",
    date: "29 Nov 2023",
    heading:
      "Unravelling the significance of Bank Realization Certificate for Indian Exporters",
    preface:
      "Explore the significance of the Bank Realization Certificate (BRC) in Indian exports. Learn about the electronic version, the process, required documents and lucrative incentives for exporters. Stay informed for strategic trade success.",
    src: "/blog/significance-of-brc",
    tag: "Multi Currency Accounts",
  },

  "swift-transfer": {
    img: "/blogs/swift-transfer/header.png",
    thumbnail: "/blogs/swift-transfer/featured.png",
    name: "Akhil Sukumaran",
    date: "17 NOV 2023",
    readMins: 5,
    heading: "SWIFT: The network powering international money transfer",
    preface:
      "Dive into the world of international finance with our comprehensive guide on SWIFT, the backbone of global money transfers. Discover how SWIFT codes work, understand the intricacies of secure transactions, and navigate the complexities of fees and processing times. Empower your cross-border financial journey with expert insights and practical tips.",
    src: "/blog/swift-transfer",
    tag: "Multi Currency Accounts",
  },
  "e-invoicing": {
    img: "/blogs/e-invoicing/header-black.png",
    thumbnail: "/blogs/e-invoicing/header-black.png",
    name: "Rishabh K",
    date: "15 OCT 2023",
    readMins: 4,
    heading: "E-Invoicing: A Comprehensive Guide for Businesses in India ",
    preface:
      "E-Invoicing in India decoded: Compliance made simple, business benefits revealed, and digital advancements explored.",
    src: "/blog/e-invoicing",
    tag: "Business",
  },
  "zero-knowledge-proof": {
    img: "/blogs/zero-knowledge-proof/header.png",
    thumbnail: "/blogs/zero-knowledge-proof/thumbnail.png",
    name: "Sanjana Pallisetti, Ansh Nigam",
    date: "14 SEPT 2023",
    readMins: 6,
    heading: "Zero-Knowledge Proof: Redefining Data Privacy",
    preface:
      "Explore the fascinating world of Zero-Knowledge Proofs and discover how they're reshaping data privacy. Dive into the future of secure digital interactions in our latest article.",
    src: "/blog/zero-knowledge-proof",
    tag: "Tech",
  },
  "empowering-exporters-rodtep": {
    img: "/blogs/empowering-exporters-rodtep/header.png",
    name: "Rishabh K",
    date: "5 SEPT 2023",
    readMins: 4,
    heading: "Empowering Exporters – The RoDTEP Scheme",
    preface:
      "Explore the RoDTEP a scheme intended to lower the cost of exported goods. Learn more on who is eligible, its benefits and advantages.",
    src: "/blog/empowering-exporters-rodtep",
    tag: "Business",
  },
  "http-redirect": {
    img: "/blogs/http-redirect/header.png",
    name: "Parag Palod",
    date: "5 SEPT 2023",
    readMins: 7,
    heading: "HTTP Redirection Demystified",
    preface:
      "Learn about different types of HTTP redirection status codes and how to use them. Business owners and marketers can use HTTP redirection to promote new pages, enhance SEO, and prevent broken links.",
    src: "/blog/http-redirect",
    tag: "Tech",
  },
  firc: {
    img: "/blogs/firc/header.png",
    name: "Parvathi Nair",
    date: "29 AUG 2023",
    readMins: 4,
    heading: "FIRC - Everything you need to know!",
    preface:
      "Explore the significance of the Foreign Inward Remittance Certificate (FIRC) for Indian exporters. Learn about its role as proof of foreign currency inflow, benefits, connection to the Bank Realization Certificate (BRC), and essential details. Discover how FIRC facilitates compliance, access to incentives, and transparent transaction records, supporting seamless cross-border trade. ",
    src: "/blog/firc",
    tag: "Multi Currency Accounts",
  },
  "choosing-the-right-mca-provider": {
    img: "/blogs/choosing-the-right-mca-provider/header.png",
    name: "Akhil Sukumaran",
    date: "21 AUG 2023",
    readMins: 4,
    heading: "Choosing the right multi-currency account provider ",
    preface:
      "Explore key factors in choosing multi-currency account providers for seamless cross border transactions.",
    src: "/blog/choosing-the-right-mca-provider",
    tag: "Multi Currency Accounts",
  },
  "hidden-costs-in-international-payments": {
    img: "/blogs/hidden-costs-in-international-payments/header.png",
    name: "Rishabh K",
    date: "11 AUG 2023",
    readMins: 4,
    heading:
      "Uncovering the Hidden Costs of International Business Transactions",
    preface:
      "Make informed financial choices by understanding the costs of international transfers. Learn about exchange rate markups, transfer fees, and more.",
    src: "/blog/hidden-costs-in-international-payments",
    tag: "Multi Currency Accounts",
  },
  "international-money-transfer": {
    img: "/blogs/international-money-transfer/header.png",
    name: "Rishabh K",
    date: "21 July 2023",
    heading: "Guide to International Money Transfer for Indian Businesses",
    preface:
      "Discover the best money transfer methods for international transfers, pros and cons of which. Find more secure and efficient ways to send and receive money globally.",
    src: "/blog/international-money-transfer",
    tag: "Multi Currency Accounts",
  },
  "open-multicurrency-account": {
    img: "/blogs/open-multicurrency-account/header.png",
    name: "Rishabh K",
    date: "3 July 2023",
    heading:
      "A Beginner’s Guide: Opening a Multi-Currency Account for Global Currency Management",
    preface:
      "Break through borders and expand your financial reach by opening a multi-currency account. Our guide walks you through the process, providing insights and tips to ensure a smooth experience as you venture into international payments.",
    src: "/blog/open-multicurrency-account",
    tag: "Multi Currency Accounts",
  },
  "international-payment-challenges": {
    img: "/blogs/challenges-of-international-payments/header.png",
    name: "Rishabh K",
    date: "23 June 2023",
    heading:
      "International Payments - The Challenges and Solutions of Cross border Payments",
    preface:
      "The four main challenges in international payments - high costs, slow transactions, security and lack of transparency and the potential solutions",
    src: "/blog/international-payment-challenges",
    tag: "Multi Currency Accounts",
  },
  "multi-currency-account-india": {
    img: "/blogs/multi-currency-account-india/header.png",
    name: "Rishabh K",
    date: "20 June 2023",
    heading:
      "What is a Multi-Currency Account - A Beginner’s Guide to Business Accounts",
    preface:
      "Learn how to effectively manage multiple currencies, conduct international transactions, & navigate the complexities of foreign exchange via multi-currency account.",
    src: "/blog/multi-currency-account-india",
    tag: "Multi Currency Accounts",
  },
  "single-sign-on-integration": {
    img: "/blogs/one-login/header.png",
    name: "Nihal Haneef",
    date: "22 Mar 2023",
    heading:
      "One Login to Rule Them All: Understanding and Integrating With Single Sign On",
    preface:
      "Master Single Sign On: A Comprehensive Guide to Understanding and Integrating One Login to Rule Them All",
    src: "/blog/single-sign-on-integration",
    tag: "Tech",
  },
  "click-click-goose": {
    img: "/blogs/click-click-goose/header.png",
    name: "Sanjana Palisetti , Shyam Santhosh",
    date: "13 Jan 2023",
    heading: "Click, Click, Goose! - What do your clicks say about you ? ",
    preface:
      "Synapse Framework: Using Behavior Analysis Patterns to Decrease Fraudulent Activity",
    src: "/blog/click-click-goose",
    tag: "Tech",
  },
  "why-alternate-payment-methods": {
    img: "/blogs/altpay/header.png",
    name: "Rishab K",
    date: "8 Sep 2022",
    heading: "What are Global Payment Methods & Why They Matter",
    preface:
      "Global Payment Methods: Improving Payment Experience and Boosting Sales",
    src: "/blog/why-alternate-payment-methods",
    tag: "Discussion",
  },
  "true-cost-of-fraud": {
    img: "/blogs/fraud/header.png",
    name: "Monica Singh",
    date: "04 Oct 2022",
    heading: "The True Cost of Fraud | Why Businesses Need Fraud Prevention",
    preface: "8 Hidden Costs of Payment Fraud",
    src: "/blog/true-cost-of-fraud",
    tag: "Business",
  },
  "payment-failure": {
    img: "/blogs/paymentFailure/header.png",
    name: "Mounika Kavuri",
    date: "03 Oct 2022",
    heading: "Payment Failure: Why it Happens and How to Avoid It",
    preface: "top 3 reasons why payments fail",
    src: "/blog/payment-failure",
    tag: "Business",
  },
  "real-time-crossborder-payments": {
    img: "/blogs/crossborderPayments/header.png",
    name: "Prachi Dharani",
    date: "29 Sept 2022",
    heading: "[Discussion] Unlocking Real Time Payments for Cross-border",
    preface: "Real time Cross Border Payments - Evolution & Way Forward",
    src: "/blog/real-time-crossborder-payments",
    tag: "Discussion",
  },
};
