import PolicyTitleWithPara from '@/Components/SmallComponents/PolicyTitleWithPara';

 function MerchantTermsSection (){





  return (
        <section className={"flex flex-col gap-10 lg:gap-12 justify-center items-center px-4 py-10 sm:px-10 sm:py-10  lg:py-20  background-custom-grey50 "}>
            <div className={"flex flex-col gap-5 max-w-3xl w-full " }>
                <p className="common-body1-text custom-text-grey900 ">This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder, as applicable and amended from time to time. This electronic record is generated by an electronic system and does not require any physical or digital signatures.</p>
                <p className="common-body1-text custom-text-grey900 ">These terms of use <strong>(&quot;Terms of Use&quot;)</strong> shall govern the relationship between PayGlocal Technologies Private Limited <strong>(&quot;PayGlocal&quot; / &quot;we&quot; / &quot;our&quot; / &quot;us&quot;)</strong> and any Person (an individual, body corporate, company / any registered user of PayGlocal Platform but not limited to PayGlocal merchants) using any or all components of PayGlocal Platform for any purpose <strong>(&quot;you&quot; / &quot;your&quot; / &quot;User&quot;)</strong> and it shall be construed as legally enforceable and binding agreement between User and PayGlocal, in addition to any other agreement (such as Technology Service Provider Agreement / Merchant Agreement or such other agreement, hereinafter collectively referred to as <strong>&quot;Agreement&quot;</strong>) that you may execute with us, for availing our Services (as defined below).</p>
                <p className="common-body1-text custom-text-grey900 ">The PayGlocal Software Application (as defined below), PayGlocal website (which shall include any social media handle, webpage/s, blog posts, operated / owned by or on behalf of PayGlocal) and/or our Services are hereinafter collectively referred to as the <strong>&quot;Platform&quot;.</strong></p>

                
            </div>
        
            {/* NATURE AND APPLICABILITY OF TERMS OF USE section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">NATURE AND APPLICABILITY OF TERMS OF USE</h4>
                <ol className="list-decimal pl-4 space-y-5">
                    <li className="common-body2-text custom-text-grey900">By using our Platform, you acknowledge that you have read these Terms of Use and that you irrevocably accept and agree to all the conditions stipulated in these Terms of Use including our Privacy Policy, and other policies as applicable to your usage of PayGlocal Platform. In the event you disagree with these Terms of Use (including any referenced policies or guidelines), please immediately terminate your use of the Platform.</li>
                    <li className="common-body2-text custom-text-grey900">These Terms of Use may be revised or altered by us at our sole discretion at any time without any prior intimation to you. The latest Terms of Use will be updated here along with the date of the change. Any such changes by us will be effective immediately. By continuing to use our Platform after any such change, you agree to be bound by the revised / amended Terms of Use and such amendments shall supersede all other Terms of Use previously accepted by you.</li>
                </ol>
            </div>

             {/* NATURE AND APPLICABILITY OF TERMS OF USE section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">SERVICES</h4>
                <p className="custom-text-grey900 common-body1-text">PayGlocal provides the following Services in a varied combination as may be specifically requested by the User.</p>
                <ol className="list-decimal pl-4  space-y-5">
                    
                    <li className="common-body2-text custom-text-grey900"><strong>Payment Aggregation and Payment Gateway Services</strong>
                        
                        <ol className=" list-inside space-y-3">
                            <li className="common-body2-text custom-text-grey900">1.1. We offer payment aggregation and payment gateway services through our Platform and/or via third-party service providers. The payment aggregation services shall mean a payment solution offered by PayGlocal to you for your Website and/or mobile application, enabling you to receive payments from Customers using various payment methods during checkout (hereinafter referred to as <strong>(&quot;PA/PG Services&quot;).</strong></li>
                        </ol>
                    </li>
                    <li className="common-body2-text custom-text-grey900"><strong>Technology Service Provider (TSP) Solutions</strong>
                        <ol className=" pl-6 space-y-3">
                            <li className="common-body2-text custom-text-grey900">2.1. We provide a TSP Solution which helps you process and manage payments from your Customers <strong>(&quot;TSP Services&quot;).</strong>Our TSP Services include the following:
                                <ol className="list-style-alphabate list-inside space-y-5" >
                                    <li className="common-body2-text custom-text-grey900">Processing of transactions in various currencies.</li>
                                    <li className="common-body2-text custom-text-grey900">Processing of transactions made through various payment methods (cards, bank transfers, etc.).</li>
                                    <li className="common-body2-text custom-text-grey900">Instructions for one time or recurring payments.</li>
                                    <li className="common-body2-text custom-text-grey900">Payment security.</li>
                                    <li className="common-body2-text custom-text-grey900">Payment experience UI for end consumer payments.</li>
                                    <li className="common-body2-text custom-text-grey900">Smart routing to multiple payment aggregators or processors.</li>
                                    <li className="common-body2-text custom-text-grey900">Transaction risk management.</li>
                                    <li className="common-body2-text custom-text-grey900">Transaction reconciliation.</li>
                                    <li className="common-body2-text custom-text-grey900">Transaction management; and</li>
                                    <li className="common-body2-text custom-text-grey900">Transaction data analytics.</li>
                                </ol>
                            </li>
                            <li className="common-body2-text custom-text-grey900">2.2. You agree that PayGlocal&apos;s role will be strictly limited to Services related to TSP and will not be that of a payment service provider.</li>
                        </ol>
                    </li>

                    <li className="common-body2-text custom-text-grey900"><strong>International Payments</strong>
                        <ol className=" pl-6 space-y-5">
                            <li className="common-body2-text custom-text-grey900">3.1. We offer international payment services as a technology platform in arrangement with an AD Category-1 Bank. Pursuant to the Cross Border Transaction Services, we enable you to receive/accept Transaction Amount/export payments from Remitters located in any Approved Jurisdictions <strong>(&quot;Cross Border Services&quot;).</strong></li>
                            <li className="common-body2-text custom-text-grey900">3.2. The Settlement Amount shall be settled from Export Collection Account to the User Bank Account within the timeline agreed with you in partnership with the AD Category-1 Bank from time to time upon receipt of the Transaction Amount in the NOSTRO Account. The Settlement Amount settled to the User Bank Account shall be made in Indian Rupees (INR). Where a foreign currency conversion is required for a settlement, the same shall be settled by applying the applicable exchange rate as of the date of the conversion.</li>
                            <li className="common-body2-text custom-text-grey900">3.3. In addition to the cross border services, PayGlocal also provides Alternative Payment Methods as a payment instrument, as detailed under specific terms of use under Annexure B.</li>
                            <li className="common-body2-text custom-text-grey900">3.4. The following amounts/charges, but not limited to, shall be deducted from the Settlement Amount:
                                <ul className="list-style-alphabate list-inside space-y-5">
                                    <li className="common-body2-text custom-text-grey900">Any excess or erroneous payment made by PayGlocal to the User.</li>
                                    <li className="common-body2-text custom-text-grey900">Fees, commission and/or charges payable to PayGlocal; and</li>
                                    <li className="common-body2-text custom-text-grey900">Any other dues from or payable by the User to PayGlocal, including without limitation any Chargebacks, if any.</li>
                                </ul>
                            </li>

                        </ol>
                    </li>

                    <li className="common-body2-text custom-text-grey900"><strong>BBPS (Bharat Bill Payment System) Payment Collection Services</strong>
                        <ol className=" pl-6 space-y-5">
                            <li className="common-body2-text custom-text-grey900">4.1. Bharat Bill Payment System is a RBI mandated system which acts as a one-stop payment solution for all utility bill payments across India &quot;Anytime Anywhere&quot;. It is intended to provide an interoperable and accessible bill payment services to customers across India (including remitters outside India) with certainty, reliability and safety of transactions. PayGlocal&apos;s BBPS Payment Collection Services offers bill collection across various utility service categories (as permissible under BBPS guidelines), through a single window.</li>
                            <li className="common-body2-text custom-text-grey900">4.2. Any Customer can make utility bill payments by accessing PayGlocal&apos;s dedicated BBPS payment page by filling-in requisite details as may be required in consonance with BBPS guidelines.</li>
                        </ol>
                    </li>
                </ol>

                
            </div>

            {/* PAYMENT, FEES, AND TAXES section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <p className="common-body1-text custom-text-grey900">In addition to the Terms of Use, the use of our Services shall be further governed by such other terms and conditions as may be agreed between the parties in the Agreement.</p>
                <h4 className="common-h4-heading">PAYMENT, FEES, AND TAXES</h4>
                <ol className="list-decimal pl-4 space-y-3">
                    <li className="common-body2-text custom-text-grey900">You agree to pay all Service fees, charges, reasonable expenses, and taxes applicable to your use of the Services, as may be informed to you by PayGlocal from time to time, in the manner as stated in the Agreement.</li>
                    <li className="common-body2-text custom-text-grey900">In the event of gross settlements, you shall pay the fees or charges along with applicable taxes within 15 (fifteen) days from the date of receipt of the invoice. If you fail to pay the fees or charges on or before the date specified by PayGlocal, you shall be liable to pay interest at a rate of 12% (twelve percent) per annum.</li>
                    <li className="common-body2-text custom-text-grey900">In the event of net settlement, the Settlement Amount shall be subject to requisite deductions including but not limited to PayGlocal Service fees, other applicable charges, and taxes from the Transaction Amount for each Transaction.</li>
                </ol>
            </div>

             {/* OBLIGATIONS OF THE USER section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">OBLIGATIONS OF THE USER</h4>
                <p className="common-body2-text custom-text-grey900">(This section is applicable to you should you fit into the criteria of a merchant providing goods and/or services)</p>
                <ol className="list-decimal pl-4 space-y-3">
                    <li className="common-body2-text custom-text-grey900">You shall maintain a fair return, cancellation or adjustment policy in accordance with type of business; disclose its return or cancellation policy to Customers at the time of purchase, not give cash refunds to a Customer in connection with a card sale, unless required by law, and not accept cash or any other item of value for issuing a card sale refund.</li>
                    <li className="common-body2-text custom-text-grey900">You shall not store/save any Customer&apos;s card details/credentials and such related data within your database or any other server accessed irrespective of being PCI-DSS compliant or otherwise. You shall be liable to comply with existing data privacy regulations from time to time and resolving all cardholder/Customer account holder disputes.</li>
                    <li className="common-body2-text custom-text-grey900">You understand that the functionality and availability of the Services depend on the policies and guidelines of platforms (Android, iOS), card schemes (Visa, MasterCard, RuPay, Maestro, Amex, etc.), banks, and related regulatory authorities as may be relevant from time to time. Any changes in regulations or policies might impact the Services.</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge that we are entitled to interrupt the use of the Service if necessary due to maintenance, security breach, repair or development of the Service upon providing written intimation to you.</li>
                    <li className="common-body2-text custom-text-grey900">You hereby provide your consent to use or process and share any type of data shared by you for the provision of this Service with third party services providers for the purpose of Services. You hereby acknowledge and agree that PayGlocal and/or its representative shall have the right to share and disclose any information, Customer data or Confidential Information with any judicial, regulatory or administrative agency or governmental authority (including RBI) to comply with the Applicable Law, rule, regulation, or request of any such authority or in connection with any legal proceedings (including court orders and subpoenas). Such disclosure shall constitute neither a violation of these Terms of Use nor a cause of liability for any damage resulting from such disclosure.</li>
                    <li className="common-body2-text custom-text-grey900">You hereby acknowledge that if there is a change of control, organizational structure, or the shareholding pattern resulting in the change of beneficial owner or ultimate beneficial owner, you shall notify us immediately at [merchant.support@payglocal.in]. Failing which, we reserve the right to suspend your Services and/or Agreement immediately without any prior notice.</li>
                    <li className="common-body2-text custom-text-grey900">You agree that PayGlocal shall solely rely on your instructions, in accordance with the provisions hereof without any obligation or duty to inquire into the genuineness or correctness of such instructions and all such communications shall be binding on you.</li>
                    <li className="common-body2-text custom-text-grey900">You shall submit upon request, all Transaction related documents including but not limited to invoice, shipping details, delivery details, business terms and contract with Customer / Remitter as maybe requested by us from time to time. Provided that in the event of delay in submission of such documents due to any reason, settlement and return of the funds to the source shall be withheld at your cost and/or may lead to termination of the Agreement. It is hereby clarified that any cost, direct or indirect, incurred for reversal of funds due to any reason whatsoever shall be borne by the User.</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge and agree that in the event any information and/or document furnished by you is inaccurate or insufficient or the transaction being processed does not align with the purpose, PayGlocal reserves the right to inform/notify the relevant third party, to reverse/suspend the Settlement Amount.</li>
                    <li className="common-body2-text custom-text-grey900">Further, if you engage in any wrongful act or omission concerning the receipt of Services, we reserve the right to terminate the Services immediately and without any notice whatsoever. PayGlocal shall also be entitled to hold the Settlement Amount until it deems fit and proper.</li>
                    <li className="common-body2-text custom-text-grey900">You shall be responsible, at your own cost, for the procurement of all equipment, software, systems, and facilities necessary for the purpose of availing the Services.</li>
                    <li className="common-body2-text custom-text-grey900">You shall submit periodic security assessment reports to us, based on our risk assessment and as required and requested by us from you.</li>
                    <li className="common-body2-text custom-text-grey900">You shall disclose comprehensive information about your policies, customer grievances, privacy policy, and other terms and conditions on your Website. Further, you shall specifically indicate the timelines for processing returns and refunds on your Website.</li>
                    <li className="common-body2-text custom-text-grey900">You shall be responsible for independent verification and validation of your Customers/Remitters, if required, without any liability on us.</li>
                    <li className="common-body2-text custom-text-grey900">You shall not store any Customer data, in any manner whatsoever, except for the limited purpose of execution of the Transactions in compliance with Applicable Law.</li>
                    <li className="common-body2-text custom-text-grey900">You shall, upon our request, execute and deliver or permit the execution and delivery of any and all such instruments and documents as we may consider necessary in order to ensure compliance to the Applicable Law and/or with the terms set out herein.</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge that PayGlocal is under no duty or obligation to ensure that any certificate, consent, notice, instruction or other communication which is or appears to be given by you in accordance with these Terms of Use is accurate, correct or duly authorized and shall be entitled to act in reliance without further enquiry upon any such certificate, consent, notice, instruction or other communication and shall not be under any duty or obligation to verify the accuracy or correctness of any statements made therein (even if such certificate, consent, notice, instruction or other communication is later reversed, modified, set aside or vacated).</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge that the Customer/Remitter data shared by you with us is governed by our Privacy Policy and we shall have the right to use/share it with any third party for the purpose of the Services, internal fraud prevention and risk assessment.</li>
                    <li className="common-body2-text custom-text-grey900">You further acknowledge, agree, and authorize us to disclose Transaction data with third party such as issuer, acquiring banks, banks, and such other Relevant Authority, as may be required, by such third party for purposes of providing Services, reconciliation, enforcement, verification, investigation, fraud, risk assessment, etc. You represent that, you have the requisite power and authorization to provide us with the Transaction data and other details and you shall be responsible for informing and obtaining such consents, as may be required, for the purpose of performing your obligations under this Agreement.</li>
                    <li className="common-body2-text custom-text-grey900">You understand and agree that onboarding with PayGlocal shall take place in accordance with our internal policies as well as guidelines prescribed by the Reserve Bank of India or any other regulatory/statutory authority(ies).</li>
                  <li className="common-body2-text custom-text-grey900">You shall co-operate with us with respect to all the Know Your Customer <strong>(KYC)</strong> compliance, Anti-Bribery/ Anti-Money Laundering <strong>(AML)</strong> / Combating Financing of Terrorism <strong>(CFT)</strong> guidelines issued by the Department of Regulation, RBI, in their &quot;Master Direction - Know Your Customer <strong>(KYC)</strong> Directions&quot; and other legal requirement. You agree that non-compliance of this Clause shall be considered as a material breach of these Terms of Use for which we reserve the right to immediately terminate our Services and User Agreement.</li>
                  <li className="common-body2-text custom-text-grey900">You shall obtain consent from the Customer to share their data with us and our third party service providers in the due course of providing the Services.</li>
                  <li className="common-body2-text custom-text-grey900">You ensure to make best efforts against:
                      <ol className="list-style-alphabate list-inside space-y-5" >
                          <li className="common-body2-text custom-text-grey900">any unauthorized or unlawful processing or alteration of the Customer information in your system.</li>
                          <li className="common-body2-text custom-text-grey900">any resultant loss or destruction of, or damage to, the Customer information due to unauthorized processing or alteration; and</li>
                          <li className="common-body2-text custom-text-grey900">unauthorized and accidental access, processing, erasure, transfer, use, modification, or other misuses of information of the Customer, and shall ensure that only authorized personnel bound by adequate confidentiality obligation shall have access to the information of the Customer on strictly &apos;need to know basis&apos;.</li>
                      </ol>
                  </li>
                  <li className="common-body2-text custom-text-grey900">You shall not accept any payments in connection with or engage in businesses, business activities or business practices, including but limited to:
                      <ol className="list-style-alphabate list-inside space-y-5" >
                          <li className="common-body2-text custom-text-grey900">Arms, Ammunition, Military, Weapons and Knives</li>
                          <li className="common-body2-text custom-text-grey900">Fireworks, explosives, or pyrotechnic devices or supplies.</li>
                          <li className="common-body2-text custom-text-grey900">Hazardous materials, combustibles, corrosives.</li>
                          <li className="common-body2-text custom-text-grey900">Alcohol / Liquor / tobacco products.</li>
                          <li className="common-body2-text custom-text-grey900">Banned / illegal drugs or other controlled substances.</li>
                          <li className="common-body2-text custom-text-grey900">Drugs and drug paraphernalia, which include illegal drugs and drug accessories, including herbal drugs, like salvia and magic mushrooms.</li>
                          <li className="common-body2-text custom-text-grey900">Drug test circumvention aids.</li>
                          <li className="common-body2-text custom-text-grey900">Any third-party processing.</li>
                          <li className="common-body2-text custom-text-grey900">Adult goods and services which includes pornography and other sexually suggestive materials (including literature, imagery and other media); escort or prostitution services.</li>
                          <li className="common-body2-text custom-text-grey900">Child pornography, which includes pornographic materials involving minors.</li>
                          <li className="common-body2-text custom-text-grey900">Copyright unlocking devices, which includes Mod chips, or other devices designed to circumvent copyright protection.</li>
                          <li className="common-body2-text custom-text-grey900">Counterfeit and unauthorized goods which includes replicas or imitations of designer goods.</li>
                          <li className="common-body2-text custom-text-grey900">Live animals.</li>
                          <li className="common-body2-text custom-text-grey900">Body parts, which includes organs, or other body parts.</li>
                          <li className="common-body2-text custom-text-grey900">Endangered species, which includes plants, animals or other organisms (including product derivatives) in danger of extinction.</li>
                          <li className="common-body2-text custom-text-grey900">Artifacts.</li>
                          <li className="common-body2-text custom-text-grey900">Bootleg / Pirated Recordings.</li>
                          <li className="common-body2-text custom-text-grey900">Brand Name misuse.</li>
                          <li className="common-body2-text custom-text-grey900">Copyrights and Trademarks.</li>
                          <li className="common-body2-text custom-text-grey900">Website access and / or website memberships of pornography or illegal sites.</li>
                          <li className="common-body2-text custom-text-grey900">Bulk marketing tools.</li>
                          <li className="common-body2-text custom-text-grey900">Multi-Level Marketing collection fees.</li>
                          <li className="common-body2-text custom-text-grey900">Matrix sites or sites using a matrix scheme approach.</li>
                          <li className="common-body2-text custom-text-grey900">Work-at-home information.</li>
                          <li className="common-body2-text custom-text-grey900">Web site promotion or Search engine registration fees.</li>
                          <li className="common-body2-text custom-text-grey900">Gambling Transactions which include lottery tickets, sports bets, memberships/ enrolment in online gambling sites, and related content</li>
                      </ol>
                      <ol className=" list-outside space-y-5 mt-5" >
                        <li className="common-body2-text custom-text-grey900">aa. Illegal goods, which includes materials, products, or information promoting illegal goods or enabling illegal acts.</li>
                        <li className="common-body2-text custom-text-grey900">ab. Wholesale currency, which includes discounted currencies or currencies, exchanges.</li>
                        <li className="common-body2-text custom-text-grey900">ac. Any product or service which is in violation of the Applicable Law.</li>
                      </ol>
                  </li>
                </ol>
            </div>
                 {/* OBLIGATIONS OF THE USER section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">ADDITIONAL OBLIGATIONS FOR USAGE OF PAYGLOCAL WEBISTE</h4>
                <p className="common-body2-text custom-text-grey900">You agree to provide true, accurate, current and complete information about yourself as and when prompted by our website. If you provide any information that is untrue, inaccurate, not updated or incomplete (or becomes untrue, inaccurate or incomplete), or PayGlocal has reasonable grounds to suspect that such information is untrue, inaccurate, not updated or incomplete, PayGlocal shall have the right to suspend or terminate your account and/or refuse any and all your current or future use of PayGlocal website (or any portion thereof) or Services in connection thereto.</p>
                <p className="common-body2-text custom-text-grey900">By making use of the PayGlocal website, and furnishing your contact details, you hereby agree that you are interested in knowing more or availing and/or purchasing various Services that PayGlocal may offer to /provide to /share with /send to you from time to time through any means including but not limited to telephone, SMS (short messaging service), electronic mail (e-mail), whatsapp or any other messaging service/mobile application or any other physical, electronic or digital means/mode. You hereby agree that PayGlocal may contact you either electronically or through phone, to understand your interest in the PayGlocal Services or overall PayGlocal Platform offering and to fulfil your requirement or complete your application. Further, you also expressly agree and authorize PayGlocal to contact you for the purpose of (i) offering or inviting your interest in availing any other services offered by PayGlocal or (ii) any follow up calls in relation to the Services provided (iii) for sending other marketing campaigns, offers, or any other information either on the through other means including but not limited to telephone, SMS (short messaging service), electronic mail (e-mail), whatsapp or any other messaging service/mobile application or any other physical, electronic or digital means/mode.</p>
                <p className="common-body2-text custom-text-grey900">You agree and authorize PayGlocal to share your information and make your details available to its partner banks/financial institutions, its group companies, affiliates, vendors, service providers and other third parties, in so far as required for providing various Services and/or to provide you with any other value-added services, in association with the Services selected by you or otherwise. You agree to receive communications through emails, telephone and/or SMS, from PayGlocal or aforementioned third parties. If you request not to receive such communication/marketing material any further, it shall be applicable prospectively only and shall not apply in respect to your data already shared by PayGlocal in accordance with this clause upon your prior consent.</p>
                <p className="common-body2-text custom-text-grey900">The usage of our website may also require You to provide consent for providing your Personal Information <strong>(&quot; PI &quot;)</strong> (including but not limited to any personal data or sensitive personal data as defined under Applicable Laws) or to authorize PayGlocal to derive your data/information from any source or public registry, as may be necessary to complete your profile or your application on our website, conduct due diligence on you, undertake KYC checks by itself or any other third party. PayGlocal adhere to best industry practices including information security, data protection and privacy law while processing such applications. However, PayGlocal shall not be liable to you against any liability or claims which may arise out of said usage, as any such PI is being collected, used, processed and shared with your explicit consent.</p>
                <p className="common-body2-text custom-text-grey900">You agree not to use the our website and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms of Use, or any local laws that might apply to you.</p>
                <p className="common-body2-text custom-text-grey900">You are prohibited from posting or transmitting to or through this website: (i) any unlawful, threatening, libellous, defamatory, obscene, pornographic or other material or content that would violate rights of publicity and/or privacy or that would violate any law or that harms minors in any way; (ii) any commercial material or content (including, but not limited to, solicitation of funds, advertising, or marketing of any good or services); (iii) any material or content that infringes, misappropriates or violates any copyright, trademark, patent right or other proprietary right of any third party; (iv) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; (v) threatens the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting to any other nation; (vi) impersonates another person; or (vii) is illegal in any other way. You shall be solely liable for any damages resulting from any violation of the foregoing restrictions, or any other harm resulting from your posting of any such content to this website.</p>
            </div>

            {/* CARD ASSOCIATION RULES section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">CARD ASSOCIATION RULES</h4>
                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900"><strong>&quot;Card Payment Network Rules&quot;</strong> refer to the written rules, regulations, releases, guidelines, processes, interpretations and other requirements (whether contractual or otherwise) imposed and adopted by the card payment networks. These card payment networks have infrastructure and processes to enable transaction authorization. The card payment networks require you to comply with all applicable guidelines, rules, and regulations formulated by them.</li>
                    <li className="common-body2-text custom-text-grey900">The card payment networks reserve the right to amend their guidelines, rules and regulations. We may be required to amend, modify or change these Terms of Use pursuant to amendments to the Card Payment Network Rules and such amendments, if any, shall be deemed to be binding on you with immediate effect.</li>
                    <li className="common-body2-text custom-text-grey900">You agree to fully comply with all programs, guidelines, requirements that may be published and/ or mandated by the card payment networks. Notwithstanding our assistance in understanding the Card Payment Network Rules, you expressly acknowledge and agree that you are assuming the risk of compliance with all provisions of the Card Payment Network Rules, regardless of whether you are aware of or have access to those provisions. MasterCard, Visa, Diners, RuPay and American Express make excerpts of their respective rules available on their internet sites.</li>
                    <li className="common-body2-text custom-text-grey900">In the event that your non-compliance of Card Payment Network Rules, results in any fines, penalties or other amounts being levied on or demanded of us by a card payment network, then without prejudice to our other rights hereunder, you shall forthwith reimburse us in an amount equal to the fines, penalties or other amount so levied or demanded or spent by us in any manner in relation to such fines, penalties and levies. If you fail to comply with your obligations towards the card payment networks, we may suspend settlement or suspend/ terminate the Services forthwith.</li>
                    </ol>
            </div>

            {/* REPRESENTATIONS AND WARRANTIES section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">REPRESENTATIONS AND WARRANTIES</h4>
                <p className="common-body2-text custom-text-grey900">This section is applicable to you should you fit into the criteria of a merchant providing goods and/or services</p>
                <p className="common-body2-text custom-text-grey900">You hereby represent and warrant, unless otherwise set forth below, that:</p>
                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900">you have requisite licenses, registrations, approvals, and permits to conduct your business in full force and is in compliance with the Applicable Laws; and</li>
                    <li className="common-body2-text custom-text-grey900">you are in compliance with the security standards, including but not limited to, Payment Card Industry Data Security Standard (PCI-DSS) and Payment Application Data Security Standard (PA-DSS), as may be applicable.</li>
                </ol>
            </div>

            {/* INTELLECTUAL PROPERTY section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">INTELLECTUAL PROPERTY</h4>
                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900">You agree that our Platform, applications, process and systems, and deliverables produced by us to perform your obligations under these Terms of Use (including without limitation, reports, compilations, and databases in any and all media) collectively which shall include service marks, logos, and trademarks are and shall remain the exclusive property of PayGlocal and are protected by copyright law or other intellectual property laws.</li>
                    <li className="common-body2-text custom-text-grey900">Save as permitted under these Terms of Use, you shall not distribute, disclose, or permit use of PayGlocal Software Application by, any third party whether in whole or in part without our express written consent.</li>
                    <li className="common-body2-text custom-text-grey900">You shall not, directly, or indirectly disassemble, reverse engineer or otherwise attempt to derive or discern the source code or internal workings of PayGlocal. You may not: (i) reproduce any part(s) of PayGlocal Software Application in any form; (ii) create any derivative work based thereon; or (iii) incorporate the Platform into other websites, electronic retrieval systems, publications or otherwise.</li>
                    <li className="common-body2-text custom-text-grey900">Nothing herein grants you the right and you shall not use or display any intellectual property including but service marks, logos, and trademarks of PayGlocal or any Alternate Payment Method (APM) Provider without written consent of PayGlocal or the relevant APM Provider.</li>
                </ol>
            </div>

              {/* TERM AND TERMINATION section  */}
              <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">TERM AND TERMINATION</h4>
                <p className="common-body2-text custom-text-grey900">This section is applicable to you should you fit into the criteria of a merchant providing goods and/or services</p>

                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900">This Term of Use shall be co-terminus and co-existent with the Agreement.</li>
                    <li className="common-body2-text custom-text-grey900">The termination of the Services provided herein shall be in accordance with the Agreement as executed between you and PayGlocal. In addition to which, PayGlocal reserves the right to terminate its Services for any violations of its policies and/or Applicable Law which at the option of PayGlocal may be with immediate effect or by providing 7 (seven) days&apos; written notice to the User for terminating its Services.</li>
                    <li className="common-body2-text custom-text-grey900">Upon termination of these Terms of Use, we shall have no obligation to retain, store or make available any data, records, or other information in relation to the Services or Transactions to you and you shall cease using the PayGlocal Software Application. Further, you shall be liable to pay us any and/or all amounts due under these Terms of Use, including but not limited to dues arising out of disputes, refund, overpaid Settlement Amount, penalties or any other charges as may be applicable to you. Similarly, PayGlocal shall facilitate the settlement of such Settlement Amounts as due to you.</li>
                </ol>
            </div>

             {/* DISCLAIMER section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">DISCLAIMER</h4>
                <p className="common-body2-text custom-text-grey900">PAYGLOCAL DISCLAIMS ALL WARRANTIES REGARDING SERVICES UNLESS EXPRESSLY AGREED IN WRITING HEREUNDER. PAYGLOCAL SHALL ENDEAVOR TO MAINTAIN ITS SERVICES/SOFTWARE/PLATFORM AND ITS SECURITY CERTIFICATION ON A BEST-EFFORT BASIS; HOWEVER, PAYGLOCAL DOES NOT WARRANT THAT THE SERVICES WILL BE FREE FROM ERROR, MALICIOUS CODE OR ANY VIRUS OR PROVIDED IN AN UNINTERRUPTED MANNER.</p>
                <p className="common-body2-text custom-text-grey900">THE PLATFORM IS PROVIDED ON  A <strong> &quot;AS IS&quot;</strong> AND <strong>&quot;AS AVAILABLE&quot;</strong>  BASIS. NEITHER WE NOR ANY OF OUR THIRD-PARTY SERVICE PROVIDERS ARE LIABLE FOR ANY TECHNICAL OR OTHER OPERATIONAL DIFFICULTIES OR PROBLEMS WHICH MAY RESULT IN LOSS OF YOUR DATA, PERSONALIZATION SETTINGS OR OTHER INTERRUPTIONS IN THE FEATURES OFFERED ON THE PLATFORM. NEITHER WE NOR ANY THIRD PARTY IS LIABLE FOR THE DELETION, LOSS, MIS-DELIVERY, TIMELINESS OR FAILURE TO STORE OR TRANSMIT ANY USER DATA, CUSTOMER/REMITTER DATA, OR YOUR PERSONALIZATION SETTINGS.</p>
            </div>

            {/* INDEMNITY section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">INDEMNITY</h4>
                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900">You shall indemnify and hold harmless PayGlocal and its directors, officers, employees, agents and its affiliates against all claims, damages, losses, costs, and expenses (including attorney&apos;s fees) which PayGlocal may suffer or incur, directly arising from or in connection with (a) commission/ omission of any act by you which is non-compliant with the Applicable Laws; or (b) any act, error, fraud, neglect or default of the Customer/Remitter or your vendor or agent, employee, sub-contractor, licensees or any other person against PayGlocal; (c) infringement of any third-party rights by your Products; or (d) non-compliance of applicable APM specific terms (as detailed under <strong>Annexure B).</strong></li>
                    <li className="common-body2-text custom-text-grey900">The indemnification rights of PayGlocal under these Terms of Use are without prejudice, independent of and in addition to, such other rights and remedies as PayGlocal may have at Applicable Law or in equity or otherwise, including but not limited to the right to seek specific performance, rescission, restitution, or other injunctive relief, none of which rights or remedies shall be affected or diminished thereby.</li>
                </ol>
            </div>

             {/* EXCLUSION section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">EXCLUSION</h4>
                <ol className="list-decimal pl-4 space-y-3 " >
                    <li className="common-body2-text custom-text-grey900">Under no circumstances, shall PayGlocal (including its officers, directors, employees, representatives, affiliates) be liable for any indirect, incidental, punitive, special, or consequential damages incurred or suffered by you or any other party arising out of or in connection with these Terms of Use, including without limitation lost revenue, loss of income, or loss of business advantage, even if (i) you or the said party suffer such damages or (ii) we have been advised of the possibility of such damages .</li>
                    <li className="common-body2-text custom-text-grey900">Except expressly provided otherwise under the Terms of Use, and to the extent permitted by Applicable Law, we shall not be liable to you or any third party for any damages or losses of any kind whatsoever, howsoever arising, regardless of the nature of the claim or the form of the cause of action.</li>
                    <li className="common-body2-text custom-text-grey900">Notwithstanding anything contained herein, our total liability shall be limited to the total fees paid for the preceding 3 (three) months from the date of such claim under these Terms of Use.</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge and agree that the exclusion in this Clause is reasonable having regard to all relevant factors, including the nature and cost of the Services provided and the allocation of risk and liability upon you.</li>
                    <li className="common-body2-text custom-text-grey900">You acknowledge that PayGlocal&apos;s Platform offering in dependent on various third-party facility providers including card networks, banks, financial institutions, internet facility provider etc. PayGlocal shall not be responsible for any disruption in our Platform offering resulting from any service disruption at such facility provider&apos;s end.</li>
                    <li className="common-body2-text custom-text-grey900">PayGlocal website may provide links to other third-party websites. However, since PayGlocal has no control over such third-party websites, you acknowledge and agree that PayGlocal is not responsible for the availability of such third-party websites and does not endorse and is not responsible or liable for any content, advertising, products or other materials on or available from such third-party websites. You further acknowledge and agree that PayGlocal shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such content, goods or services available on or through any such third-party websites. Such third-party websites may have separate terms and conditions and privacy policy, which are independent of PayGlocal&apos;s and therefore, we advise you to read the terms of use and conditions available on such websites before you access any such third- party website.</li>
                </ol>
            </div>

            {/* FORCE MAJEURE section  */}
            {/* component for only title and paragraphs  */}
            <PolicyTitleWithPara title={'FORCE MAJEURE'}
                paras={[
                    {text:'Except for the obligation to pay for Services delivered, non-performance of either party shall be excused to the extent that performance is rendered impossible by strike, fire, flood, other natural disasters, governmental acts, acts of terror or orders or restrictions, failure of suppliers, market disturbance, or act of God, epidemic, pandemic (including the Covid-19 pandemic), quarantine, civil commotion or any other reason where failure to perform is beyond the control and not caused by the negligence of the non-performing party (&quot;Force Majeure Event&quot;). The affected party shall promptly notify the non-affected party of the nature and extent of the circumstances giving rise to the Force Majeure Event.'},
                    {text:"For the avoidance of doubt, Force Majeure Event shall not include (a) financial distress nor the inability of either party to make a profit or avoid a financial loss, (b) changes in market prices or conditions, or (c) a party's financial inability to perform its obligations hereunder."}
            ]}/>

             {/* WAIVER section  */}
            <PolicyTitleWithPara title={'WAIVER'}
                paras={[
                    {text:"Any failure or delay by PayGlocal to enforce or exercise any provision of these Terms of Use, or any related right, shall not constitute a waiver by PayGlocal of that provision or right. The exercise of one or more of PayGlocal 's rights hereunder shall not be a waiver of, or preclude the exercise of, any other rights or remedies available to PayGlocal under these Terms or in law or at equity. Any waiver of any provision shall only be effective if made in writing and executed by a duly authorized officer of PayGlocal."},
            ]}/>

             {/* NOTICE section  */}
             <PolicyTitleWithPara title={'NOTICE'}
                paras={[
                    {text:'All notices, demands and other communications required or desired to be given hereunder shall be in writing and shall be deemed to be given: (i) if personally delivered, upon such delivery; (ii) if mailed by certified mail, return receipt requested, postage pre-paid, to such address listed in these Terms of Use, on receipt of such mail; or (iii) if delivered by electronic mail, as soon as it has been sent by the sender (provided that the sender does not receive a notification that the e-mail was not sent). Addresses may be changed by written notice given as provided herein and signed by the party giving the notice.'},
            ]}/>

             {/* GOVERNING LAW AND JURISDICTION section  */}
            <PolicyTitleWithPara title={'GOVERNING LAW AND JURISDICTION'}
                paras={[
                    { text: 'These Terms of Use shall be interpreted, construed, and enforced in accordance with the laws of India. The courts of Bengaluru, Karnataka, India shall have exclusive jurisdiction in any matter related with these Terms of Use.' },
            ]} />

          {/* DISPUTE RESOLUTION section  */}
          <div className="flex flex-col gap-5 max-w-3xl w-full">
              <h4 className="common-h4-heading">DISPUTE RESOLUTION</h4>
              <ol className="list-decimal pl-4 space-y-3 " >
                  <li className="common-body2-text custom-text-grey900">All or any disputes arising out of these Terms of Use, including the interpretation and validity of the terms thereof and the respective rights and obligations of the parties, shall be settled amicably by mutual discussion in good faith (&quot;Negotiations&quot;).</li>
                  <li className="common-body2-text custom-text-grey900">In the event a dispute is not resolved within 30 (thirty) days of the commencement of the Negotiations, the dispute shall be referred to and resolved by arbitration in accordance with the Arbitration and Conciliation Act, 1996 and rules framed thereunder, as amended from time to time. The arbitration proceedings shall be held in Bangalore, India. The courts of Bangalore shall have exclusive jurisdiction in relation to this Agreement, the arbitration and all matters arising in connection herewith.</li>
              </ol>
          </div>

          {/* MISCELLANEOUS section  */}
          <div className="flex flex-col gap-5 max-w-3xl w-full">
              <h4 className="common-h4-heading">MISCELLANEOUS</h4>
              <ol className="list-decimal pl-4 space-y-3 " >
                  <li className="common-body2-text custom-text-grey900">You acknowledge and agree that all Transactions, wherever originated, may be processed by PayGlocal or may be processed on behalf of PayGlocal by one or more of the service providers. All Transactions, wherever originated, shall be processed in accordance with the laws and regulations of the jurisdiction where the Transaction is being processed, including but not limited to, those laws relating to anti-money laundering, anti-terrorism, and foreign asset control. PayGlocal does not make any representation or statement, or endorsement of the quality, safety or legality of any services provided by any service provider and shall not be liable to you for any delays or losses incurred as a consequence of PayGlocal making such enquiries as they deem necessary in order to discharge their legal and regulatory responsibilities.</li>
                  <li className="common-body2-text custom-text-grey900">You confirm and agree that a person who is not a party to these Terms of Use shall have no rights to enforce any term of these Terms of Use or have the benefit of any of its terms.</li>
                  <li className="common-body2-text custom-text-grey900">In the event that any part of this Term of Use shall be held by a court of competent jurisdiction to be unlawful or otherwise unenforceable, the remainder of these Term of Use shall remain in full force and effect to the maximum extent possible.</li>
                  <li className="common-body2-text custom-text-grey900">Any delay in enforcing a party&apos;s rights under these Terms of Use or any waiver as to a particular default or other matter shall not constitute a waiver of such party&apos;s rights to the future enforcement of its rights under these Terms of Use, except with respect to an express written and signed waiver relating to a particular matter for a particular period of time.</li>
                  <li className="common-body2-text custom-text-grey900">PayGlocal is an independent contractor for all purposes. Nothing in these Terms of Use will be construed as constituting a partnership, joint venture, or agency with you.</li>
              </ol>
          </div>


             {/* GRIEVANCE REDRESSAL section  */}
             <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">GRIEVANCE REDRESSAL</h4>
                <p className="common-body2-text custom-text-grey900">We have appointed a Nodal Officer to address any concerns or grievances against the Platform. In the event you have any such grievances, please contact our Nodal Officer at:
                    <br />Name: Ritu Verma
                    <br />Email ID: <a href="mailto:grievances@payglocal.in" className='custom-text-blue1'>grievances@payglocal.in</a> 
                    </p>
            </div>
            <div className="max-w-3xl w-full">
                <h4 className="common-h4-heading font-bold underline">ANNEXURE-A</h4>
            </div>

            {/* DEFINITIONS section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">DEFINITIONS</h4>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Agreement&quot;</strong> shall mean an agreement executed by and between PayGlocal and the User relating to the Services provided by PayGlocal.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Alternate Payment Method&quot;</strong> (APM) shall mean any form of non-card payments for conducting international transactions, as detailed under Annexure B below (as amended from time to time) and which shall not include payments in crypto currencies. In order to avail the same, APM shall have to be a legally valid alternate (non-card) payment method in the Customer&apos;s / remitter&apos;s country.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;APM Provider/s&quot;</strong> shall mean a payment institution authorized by applicable jurisdictional authority/regulatory body for providing/enabling APM as a payment mode for facilitating payments between Customer and Merchant.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Applicable Laws&quot;</strong> shall mean and include without limitation Foreign Exchange Management Act, 1999 including amendments and regulations made thereunder, read along with any guidelines or directions issued by regulatory authority including but not limited to the guidelines with respect to Payment Aggregator and Payment Gateways, Combating Financing of Terrorism <strong>(CFT),</strong> Know Your Customer <strong>(KYC),</strong> Anti Money Laundering <strong>(AML)</strong> (as may be amended, supplemented, and modified from time to time), Office of Foreign Assets Control rules and such other Data Protection Law, taxation law or other laws as may be applicable to the parties in their respective jurisdiction from time to time.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Approved Jurisdiction&quot;</strong> shall mean the geography (country) in which the User and the Customer / Remitter are authorized to transact between each other, and which excludes the grey and black listed countries under the Financial Action Task Force (FATF) or any other high risk country, as may be notified by the Reserve Bank of India (RBI) or other competent regulatory bodies, from time to time.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Authorized Dealer Category-I/AD Category-1 Bank&quot;</strong> shall mean a designated category-1 authorized dealer bank deals with foreign exchange for purposes specified from time to time. &quot;Business Day&quot; shall mean (except where otherwise indicated) a day, not being a Sunday or a public/bank holiday in India or the country from where the international payment is expected to be received.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Chargeback&quot;</strong> shall mean the reversal requested by a Customer/Remitter from their bank of the amount of Transaction charged by the User.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Confidential Information&quot;</strong> shall mean all business, technical, financial, or other information including but not limited to ideas, concepts, know-how (whether patentable, copyrightable or not), Customer&apos;s information stored or available with the User, computer programs and software programs created or exchanged between the parties under these terms of Use and shall include personal data.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Customer/ Remitter&quot;</strong> shall mean any person who purchases Products from the User using the Services.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Data Protection Laws&quot;</strong> shall mean and include without limitation the Information Technology Act, 2000 (IT Act), Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011 <strong>(&apos;SPDI Rules&apos;)</strong> the Information Technology (The Indian Computer Emergency Response Team and the Manner of Performing Functions and Duties) Rules, 2013 (CERT-In Rules) (as may be amended, supplemented, and modified from time to time ) including but not limited to any data protection laws, regulation, order, mandatory guidance, or directives or requirements of any regulatory body which relates to the protection of individuals with regard to the processing of personal data to which PayGlocal and User are subjected.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;User Bank Account&quot;</strong> shall mean a bank account held by the User for receiving the payment of the Settlement Amount.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Export Collection Account&quot;</strong> shall mean a bank account held by the AD Category-1 bank for PayGlocal in India specifically designated for the purpose of provisioning the Settlement Amount to the Entity Bank Account.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;NOSTRO Account&quot;</strong> shall mean a bank account designated to PayGlocal in arrangement with AD Category-1 Bank, in a foreign currency for the purpose of receiving electronic remittance from the Customer/Remitter.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Participating Bank&quot;</strong> shall mean the banks participating in and supporting the relevant Alternate Payment Method.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;PayGlocal Software Application&quot;</strong> shall mean the PayGlocal technology including but not limited to its websites, software, platforms, application programming interfaces, and other online tools, application for facilitating the Services by PayGlocal.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Products&quot;</strong> shall mean one or more tangible or intangible goods and/or services offered for sale by the User to its Customers/Remitter.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Relevant Authority&quot;</strong> means any regulatory authority or acquiring bank / partner or card scheme association that authorizes or settles any dispute between card payment systems and Customers or any other relevant authority governing the Transactions hereunder in the Approved Jurisdiction.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Services&quot;</strong> shall mean collective services of PA/PG Services, TSP Services and Cross Border Services.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Settlement Amount&quot;</strong> shall mean the Transaction Amount after deduction of the charges, penalties,levies, refunds, chargeback, fees (if applicable) or any other adjustments from time to time in relation to each Transaction, which shall be settled in the User Bank Account from Export Collection Account.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Transaction&quot;</strong> shall mean the purchase of Product by the Customer/Remitter and the settlement of the Settlement Amount to the User in the User Bank Account.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Transaction Amount&quot;</strong> shall mean the amount or payment received from the Customer/Remitter under the instructions of the User by PayGlocal in connection with the Transaction.</p>
                <p className="common-body2-text custom-text-grey900"><strong>&quot;Website&quot;</strong> shall mean the website and/or the mobile application established by the User for the purposes of enabling its Customers/Remitters to purchase the Products.</p>


            </div>
            <div className="max-w-3xl w-full">
                <h4 className="common-h4-heading font-bold underline  ">ANNEXURE-B</h4>
            </div>

            {/* SPECIFIC TERMS OF USE section  */}
            <div className="flex flex-col gap-5 max-w-3xl w-full">
                <h4 className="common-h4-heading">SPECIFIC TERMS OF USE</h4>
                <ol className="list-decimal pl-4 space-y-3 " >
                    {/* eps */}
                    <li className="common-body2-text custom-text-grey900">eps
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Real-time Bank Transfer</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>

                              {/* Row 3 */}
                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>

                              {/* Row 4 */}
                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">EUR 1.00/- (Euro One Only) per Transaction</td>
                              </tr>

                              {/* Row 5 */}
                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As per Regulatory guidelines</td>
                              </tr>

                              {/* Row 6 */}
                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Prohibited goods and services listed in Clause IV (13) of these terms of Use</td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5" >
                        <li className="common-body2-text custom-text-grey900">eps is an Alternative Payment Method enabling receipt of a real time confirmation of the Transaction facilitated by the Participating Banks. eps offers a special guarantee in the form of an abstract promissory note meaning that you are not only provided with a confirmation statement concerning the completion of the online transfer, but a positive confirmation statement is combined with a guarantee issued by the eps Participating Banks as an abstract promissory note. A guaranteed event occurs if a positive bank transfer confirmation is received by you even if an eps bank transfer order is not carried out.</li>
                        <li className="common-body2-text custom-text-grey900">You are obliged to strictly comply with the relevant provisions of the Austrian Gaming Act and shall only accept funds for games of chance if the same is legally permitted under the laws of Austria. You acknowledge and confirm that you are aware that any violation of provision of the Terms of Use may be subject to fines by the Relevant Authority and you shall remain solely liable for any such violation at all times.</li>
                      </ol>
                    </li>

                    {/* Giropay */}
                    <li className="common-body2-text custom-text-grey900">Giropay
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Real-time Bank Transfer</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">EUR 1.00/- (Euro One Only) per Transaction</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As per Regulatory guidelines</td>
                              </tr>


                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">In addition to any prohibited goods or services listed in Clause IV (13) of these terms of Use: Payment instruments (cash, savings or e-money, currencies including virtual currencies such as bitcoins, as well as checks) as far as the recipient of the payment instrument can&apos;t be identified by the acquirer or the User, except vouchers or stored value products</td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5" >
                        <li className="common-body2-text custom-text-grey900">giropay is an Alternative Payment Method where the User shall receive a real time confirmation of the Transaction. Information on the beneficiary of a payment Transaction and the intended use of a Transaction is automatically entered into the online banking mask of the Customer.</li>
                        <li className="common-body2-text custom-text-grey900">giropay is restricted to Customers with access to an online banking compatible account held at an authorized credit institution based in Germany. PayGlocal does not guarantee that all German bank accounts are giropay compatible.</li>
                        <li className="common-body2-text custom-text-grey900">giropay offers a special guarantee inform of an abstract promissory note meaning that the User is provided with a confirmation statement concerning the completion of the online transfer and a positive confirmation statement combined with a guarantee issued by the giropay Participating Banks as an abstract promissory note even if a giropay bank transfer order is not carried out.</li>
                        <li className="common-body2-text custom-text-grey900">The payment guarantees passed on by PayGlocal in the scope of the giropay Alternative Payment Method are in each case limited to an amount of EUR 10,000/- (Euro Ten Thousand Only) per Transaction, even if the Transaction executed is for a higher amount.</li>
                        <li className="common-body2-text custom-text-grey900">The User shall report events that requires reliance on the giropay guarantee to PayGlocal. The User&apos;s claims resulting from the giropay payment guarantee shall expire 06 (six) weeks after receipt of a positive bank transfer confirmation unless the User reports the claim from the payment guarantee to PayGlocal in writing without delay before this date.</li>
                        <li className="common-body2-text custom-text-grey900">On selecting giropay as the desired payment method, the User is prohibited to request the Customer ́s data, in particular personal data such as International Bank Account Number (IBAN) or names.</li>
                      </ol>
                    </li>

                    {/* GrabPay- Singapore */}
                    <li className="common-body2-text custom-text-grey900">GrabPay- Singapore
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Wallet</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">SGD 0.01 per transaction</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">SGD 3,000/- (Singapore Dollars Three Thousand Only) for basic wallet users; SGD 5,000/- (Singapore Dollars Five Thousand Only) for premium wallet users</td>
                              </tr>


                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As provided under GrabPay&apos;s terms of use provided at: <br /> <a href="https://www.grab.com/sg/terms-policies/" className="custom-text-blue1">https://www.grab.com/sg/terms-policies/</a></td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5 " >
                        <li className="common-body2-text custom-text-grey900">The User shall abide, by the GrabPay terms of use, which include Grabpay&apos;s Privacy Policy and Acceptable Use Policy at: <a href="https://www.grab.com/sg/terms-policies/" className="custom-text-blue1">https://www.grab.com/sg/terms-policies/</a></li>
                        <li className="common-body2-text custom-text-grey900">The User shall not impose a surcharge or any other fee for accepting GrabPay as an Alternative Payment Method without prior written consent from GrabPay. This shall not prevent User from charging a handling fee in connection with the sale of goods or services.</li>
                        <li className="common-body2-text custom-text-grey900">Refunds shall be initiated only through the GrabPay system interface provided by PayGlocal. In the event an User uses any APM for the refund, including but not limited to bank remittance or cash refund, GrabPay shall not be a party in any way and such refund shall be between the User and the Customer.</li>
                        <li className="common-body2-text custom-text-grey900">Upon request, the User shall cooperate as may be necessary to investigate a Transaction, including providing to PayGlocal any documentation and/or information related to a Transaction within 14 (fourteen) days and shall ensure to take all steps necessary to comply with this cooperation.</li>
                        <li className="common-body2-text custom-text-grey900">Based on this investigation, GrabPay shall decide if a Transaction needs to be refunded to the Customer. The User acknowledges that GrabPay&apos;s decision shall be final and PayGlocal will execute the refund if and as instructed by GrabPay. If a refund to the Customer is required, the User shall be fully liable for any refund amount as well as any other costs directly associated with such refund.</li>
                        <li className="common-body2-text custom-text-grey900">GrabPay reserves the right to impose restrictions to the Service at any time, including rejecting or limiting Transactions.</li>
                        <li className="common-body2-text custom-text-grey900">The User shall, treat GrabPay on par with any other Alternate Payment Methods offered, on its Websites, advertising and promotional materials and its other external publications. In particular:
                            <ol className="list-style-roman list-inside space-y-5 pl-3">
                                <li className="common-body2-text custom-text-grey900">The placement of the GrabPay logo and selection buttons are substantially similar to the placement of alternative means of payment, and that the prominence of the GrabPay logo and selection buttons are equal to other means of payment.</li>
                                <li className="common-body2-text custom-text-grey900">GrabPay receives treatment equal to alternative means of payment in the checkout flow of an User&apos;s point of sale, and in the terms, conditions, restrictions, or fees offered or given by the User to its Customers; and</li>
                                <li className="common-body2-text custom-text-grey900">Nothing inhibits or disadvantages a Customer&apos;s selection of GrabPay, dissuades the user from using GrabPay, or encourages the Customer to use any other payment method.</li>
                            </ol>
                        </li>

                      </ol>
                    </li>

                      {/* MyBank */}
                      <li className="common-body2-text custom-text-grey900">MyBank
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Real-time Bank Transfer</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">EUR 0.01 per Transaction</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As per Regulatory guidelines</td>
                              </tr>


                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">In addition to those prohibited goods and services listed in Clause IV (13) of these terms of Use: Activities which could be punishable as endangerment of minors, for infringement of works protected by intellectual property rights and means of payment, the non-compliance with the protection of personal data, with systems automated data processing, acts of money laundering, non-compliance relating to gambling and betting, horse racing, lotteries and provisions relating to conditions of exercise of regulated professions</td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5 " >
                        <li className="common-body2-text custom-text-grey900">MyBank is an Alternative Payment Method where the User enabling receipt of real time confirmation of the Transaction. It allows the User to exchange information in real time through trusted parties to provide each other with the necessary level of trust and certainty that a payment has been initiated or that a valid mandate has been sent.</li>
                        <li className="common-body2-text custom-text-grey900">The User agrees on being informed about the effects of the e-authorization result:
                            <ol className="list-style-roman list-inside space-y-5 pl-3">
                                <li className="common-body2-text custom-text-grey900">An e-authorization result shall constitute a factual confirmation of the bank of the Customer.</li>
                                <li className="common-body2-text custom-text-grey900">The User shall not have any claims, benefits, or rights against PayGlocal in connection with the MyBank solution, and PayGlocal shall not be liable to the User for any such claims, benefits or rights arising out of or in connection with the use of the MyBank solution. The User acknowledges that MyBank is not a guaranteed Alternative Payment Method.</li>
                            </ol>
                        </li>
                        <li className="common-body2-text custom-text-grey900">The User may use the MyBank Logo in the manner as set forth in the MyBank Style Guide for Businesses found at the following website <a href="https://www.mybank.eu/mybank/my" className="custom-text-blue1">https://www.mybank.eu/mybank/my</a></li>

                      </ol>
                    </li>

                    {/* Sofort */}
                    <li className="common-body2-text custom-text-grey900">Sofort
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Real-time Bank Transfer</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">EUR 1/- (Euro One Only) per Transaction</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As per Regulatory guidelines</td>
                              </tr>


                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Prohibited goods and services listed in Clause IV (13) of these terms of Use.</td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5" >
                        <li className="common-body2-text custom-text-grey900">Sofort is an Alternative Payment Method wherein the User receives a real time confirmation of the Transaction.</li>
                        <li className="common-body2-text custom-text-grey900">The User acknowledges that Transactions with Sofort may be executed by most standard banks in the countries listed in the relevant product sheets provided to the User. PayGlocal reserves the right to offer Sofort in other countries, as well. PayGlocal does not guarantee wire transfer option to Customer through every bank account in Approved Jurisdiction or any other country. Further, PayGlocal does not guarantee that Transactions which can currently be made with Sofort via individual banks or countries will continue to remain possible in the future.</li>
                        <li className="common-body2-text custom-text-grey900">PayGlocal grants to the User the non-exclusive, temporary, and limited right for the term of the Agreement to use itself or to offer the Sofort Transfer-Software to its Customers. The User is obliged to integrate the software into its systems in such a way that the URL and the SSL-certificate of Sofort are recognisable and verifiable.</li>
                      </ol>
                    </li>

                     {/* Trustly */}
                     <li className="common-body2-text custom-text-grey900">Trustly
                      <table className="w-full border-collapse border custom-border-grey200">
                          <tbody>

                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text  custom-text-grey900 border-r custom-border-grey200">Payment Type</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Real-time Bank Transfer</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Chargeback Risk</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">No</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Refund Possibility</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Yes</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Minimum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">Subject to conditions imposed by the Customers bank (usually EUR 0.01 per Transaction)</td>
                              </tr>


                              <tr className="border-b custom-border-grey200">
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Transaction Maximum</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">As per Regulatory guidelines</td>
                              </tr>


                              <tr>
                                  <td className="px-4 py-4 common-body2-text font-medium custom-text-grey900 border-r custom-border-grey200">Specific Prohibited Goods and Services or Payment Instruments</td>
                                  <td className="px-4 py-4 common-body2-text custom-text-grey900">In addition to those prohibited goods and services listed in Clause IV (13) of these terms of Use: Money remittance where the User does not hold a valid bank license in accordance with local requirements from applicable authorities; Shell banks as defined under FATF recommendations; asset-holding vehicles like trusts, foundations (apart from charity foundations), private wealth management structures; , antiques or collectors&apos; items; Fortune tellers, mediums and other services speculating around supernatural phenomena; Computer (including remote) tech support/performance optimization/virus removal solutions (sellers/authorized resellers of downloadable and installable antivirus software fall outside of scope of this prohibition); Nazi and fascist memorabilia and militaria (both replicas and original artefacts) excluding auction houses (as it is assumed that those are acting clearly for needs of collectors), and marketplaces (as it is assumed that those have relevant policies and content controls in place)</td>
                              </tr>
                          </tbody>
                      </table>
                      <ol className="list-style-alphabate list-inside space-y-5" >
                        <li className="common-body2-text custom-text-grey900">Trustly is an Alternative Payment Method where the User receives a real time confirmation of the Transaction.</li>
                        <li className="common-body2-text custom-text-grey900">Once Trustly is selected as a payment mechanism by the Customer, the Customer can pay through Participating Banks by bank transfer method which shall be fully online and automated.</li>
                        <li className="common-body2-text custom-text-grey900">The User is obliged to display Trustly&apos;s logotype(s)/ trademark(s) in an appealing and appropriate manner and in accordance with the applicable service presentation requirements as set out at: <a href='https://trustly.com/en/developer/documents' className='custom-text-blue1'>https://trustly.com/en/developer/documents</a ></li>
                        <li className="common-body2-text custom-text-grey900">The User acknowledges and agrees that its Customers shall be made aware, that the Trustly service is dependent on the full functionality of third-party systems, primarily, banks and that Trustly does not guarantee the functionality of its service in the event of failures, malfunctions, or adjustments within such third-party systems.</li>
                      </ol>
                    </li>

                </ol>
            </div>



          
        </section>
    )
}

export default MerchantTermsSection;
